(function(e){function m(){}function u(a,b){return function(){a.apply(b,arguments)}}function r(a){if("object"!==typeof this)throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this._state=0;this._handled=!1;this._value=void 0;this._deferreds=[];d(a,this)}function w(a,c){for(;3===a._state;)a=a._value;0===a._state?a._deferreds.push(c):(a._handled=!0,r._immediateFn(function(){var f=1===a._state?c.onFulfilled:c.onRejected;if(null===
f)(1===a._state?q:b)(c.promise,a._value);else{try{var d=f(a._value)}catch(n){b(c.promise,n);return}q(c.promise,d)}}))}function q(c,f){try{if(f===c)throw new TypeError("A promise cannot be resolved with itself.");if(f&&("object"===typeof f||"function"===typeof f)){var g=f.then;if(f instanceof r){c._state=3;c._value=f;a(c);return}if("function"===typeof g){d(u(g,f),c);return}}c._state=1;c._value=f;a(c)}catch(v){b(c,v)}}function b(b,c){b._state=2;b._value=c;a(b)}function a(a){2===a._state&&0===a._deferreds.length&&
r._immediateFn(function(){a._handled||r._unhandledRejectionFn(a._value)});for(var b=0,c=a._deferreds.length;b<c;b++)w(a,a._deferreds[b]);a._deferreds=null}function c(a,b,c){this.onFulfilled="function"===typeof a?a:null;this.onRejected="function"===typeof b?b:null;this.promise=c}function d(a,c){var f=!1;try{a(function(a){f||(f=!0,q(c,a))},function(a){f||(f=!0,b(c,a))})}catch(v){f||(f=!0,b(c,v))}}if(!e.Promise){var f=setTimeout;r.prototype["catch"]=function(a){return this.then(null,a)};r.prototype.then=
function(a,b){var f=new this.constructor(m);w(this,new c(a,b,f));return f};r.all=function(a){var b=Array.prototype.slice.call(a);return new r(function(a,c){function f(h,g){try{if(g&&("object"===typeof g||"function"===typeof g)){var e=g.then;if("function"===typeof e){e.call(g,function(a){f(h,a)},c);return}}b[h]=g;0===--d&&a(b)}catch(C){c(C)}}if(0===b.length)return a([]);for(var d=b.length,g=0;g<b.length;g++)f(g,b[g])})};r.resolve=function(a){return a&&"object"===typeof a&&a.constructor===r?a:new r(function(b){b(a)})};
r.reject=function(a){return new r(function(b,c){c(a)})};r.race=function(a){return new r(function(b,c){for(var f=0,d=a.length;f<d;f++)a[f].then(b,c)})};r._immediateFn="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){f(a,0)};r._unhandledRejectionFn=function(a){"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a)};r._setImmediateFn=function(a){r._immediateFn=a};r._setUnhandledRejectionFn=function(a){r._unhandledRejectionFn=a};e.Promise=
r}})(this);
(function(e,m){e.ResizeObserver=m()})(this,function(){function e(a){for(var b=[],c=arguments.length-1;0<c--;)b[c]=arguments[c+1];return b.reduce(function(b,c){return b+(parseFloat(a["border-"+c+"-width"])||0)},0)}var m=function(){function a(a,b){var c=-1;a.some(function(a,h){return a[0]===b?(c=h,!0):!1});return c}return"undefined"!==typeof Map?Map:function(){function b(){this.__entries__=[]}var c={size:{configurable:!0}};c.size.get=function(){return this.__entries__.length};b.prototype.get=function(b){b=
a(this.__entries__,b);return(b=this.__entries__[b])&&b[1]};b.prototype.set=function(b,c){var h=a(this.__entries__,b);~h?this.__entries__[h][1]=c:this.__entries__.push([b,c])};b.prototype["delete"]=function(b){var c=this.__entries__;b=a(c,b);~b&&c.splice(b,1)};b.prototype.has=function(b){return!!~a(this.__entries__,b)};b.prototype.clear=function(){this.__entries__.splice(0)};b.prototype.forEach=function(a,b){void 0===b&&(b=null);for(var c=0,h=this.__entries__;c<h.length;c+=1){var f=h[c];a.call(b,f[1],
f[0])}};Object.defineProperties(b.prototype,c);return b}()}(),u="undefined"!==typeof window&&"undefined"!==typeof document&&window.document===document,r="undefined"!==typeof global&&global.Math===Math?global:"undefined"!==typeof self&&self.Math===Math?self:"undefined"!==typeof window&&Math===Math?window:Function("return this")(),w=function(){return"function"===typeof requestAnimationFrame?requestAnimationFrame.bind(r):function(a){return setTimeout(function(){return a(Date.now())},1E3/60)}}(),q=function(a,
b){function c(){d&&(d=!1,a());g&&f()}function h(){w(c)}function f(){var a=Date.now();if(d){if(2>a-e)return;g=!0}else d=!0,g=!1,setTimeout(h,b);e=a}var d=!1,g=!1,e=0;return f},b="top right bottom left width height size weight".split(" "),a="undefined"!==typeof MutationObserver,c=function(){this.mutationEventsAdded_=this.connected_=!1;this.mutationsObserver_=null;this.observers_=[];this.onTransitionEnd_=this.onTransitionEnd_.bind(this);this.refresh=q(this.refresh.bind(this),20)};c.prototype.addObserver=
function(a){~this.observers_.indexOf(a)||this.observers_.push(a);this.connected_||this.connect_()};c.prototype.removeObserver=function(a){var b=this.observers_;a=b.indexOf(a);~a&&b.splice(a,1);!b.length&&this.connected_&&this.disconnect_()};c.prototype.refresh=function(){this.updateObservers_()&&this.refresh()};c.prototype.updateObservers_=function(){var a=this.observers_.filter(function(a){return a.gatherActive(),a.hasActive()});a.forEach(function(a){return a.broadcastActive()});return 0<a.length};
c.prototype.connect_=function(){u&&!this.connected_&&(document.addEventListener("transitionend",this.onTransitionEnd_),window.addEventListener("resize",this.refresh),a?(this.mutationsObserver_=new MutationObserver(this.refresh),this.mutationsObserver_.observe(document,{attributes:!0,childList:!0,characterData:!0,subtree:!0})):(document.addEventListener("DOMSubtreeModified",this.refresh),this.mutationEventsAdded_=!0),this.connected_=!0)};c.prototype.disconnect_=function(){u&&this.connected_&&(document.removeEventListener("transitionend",
this.onTransitionEnd_),window.removeEventListener("resize",this.refresh),this.mutationsObserver_&&this.mutationsObserver_.disconnect(),this.mutationEventsAdded_&&document.removeEventListener("DOMSubtreeModified",this.refresh),this.mutationsObserver_=null,this.connected_=this.mutationEventsAdded_=!1)};c.prototype.onTransitionEnd_=function(a){var c=a.propertyName;void 0===c&&(c="");b.some(function(a){return!!~c.indexOf(a)})&&this.refresh()};c.getInstance=function(){this.instance_||(this.instance_=new c);
return this.instance_};c.instance_=null;var d=function(a,b){for(var c=0,h=Object.keys(b);c<h.length;c+=1){var f=h[c];Object.defineProperty(a,f,{value:b[f],enumerable:!1,writable:!1,configurable:!0})}return a},f=function(a){return a&&a.ownerDocument&&a.ownerDocument.defaultView||r},k={x:0,y:0,width:0,height:0},p=function(){return"undefined"!==typeof SVGGraphicsElement?function(a){return a instanceof f(a).SVGGraphicsElement}:function(a){return a instanceof f(a).SVGElement&&"function"===typeof a.getBBox}}(),
g=function(a){this.broadcastHeight=this.broadcastWidth=0;this.contentRect_={x:0,y:0,width:0,height:0};this.target=a};g.prototype.isActive=function(){var a=this.target;if(u)if(p(a)){var b=a.getBBox();b={x:0,y:0,width:b.width,height:b.height}}else{var c=a.clientWidth,d=a.clientHeight;if(c||d){var g=f(a).getComputedStyle(a);b={};for(var t=0,n=["top","right","bottom","left"];t<n.length;t+=1){var m=n[t];b[m]=parseFloat(g["padding-"+m])||0}var v=b.left+b.right;m=b.top+b.bottom;t=parseFloat(g.width)||0;
n=parseFloat(g.height)||0;"border-box"===g.boxSizing&&(Math.round(t+v)!==c&&(t-=e(g,"left","right")+v),Math.round(n+m)!==d&&(n-=e(g,"top","bottom")+m));a!==f(a).document.documentElement&&(a=Math.round(t+v)-c,d=Math.round(n+m)-d,1!==Math.abs(a)&&(t-=a),1!==Math.abs(d)&&(n-=d));b={x:b.left,y:b.top,width:t,height:n}}else b=k}else b=k;this.contentRect_=b;return b.width!==this.broadcastWidth||b.height!==this.broadcastHeight};g.prototype.broadcastRect=function(){var a=this.contentRect_;this.broadcastWidth=
a.width;this.broadcastHeight=a.height;return a};var v=function(a,b){var c=b.x,f=b.y,h=b.width;b=b.height;var g=Object.create(("undefined"!==typeof DOMRectReadOnly?DOMRectReadOnly:Object).prototype);d(g,{x:c,y:f,width:h,height:b,top:f,right:c+h,bottom:b+f,left:c});d(this,{target:a,contentRect:g})},n=function(a,b,c){this.activeObservations_=[];this.observations_=new m;if("function"!==typeof a)throw new TypeError("The callback provided as parameter 1 is not a function.");this.callback_=a;this.controller_=
b;this.callbackCtx_=c};n.prototype.observe=function(a){if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");if("undefined"!==typeof Element&&Element instanceof Object){if(!(a instanceof f(a).Element))throw new TypeError('parameter 1 is not of type "Element".');var b=this.observations_;b.has(a)||(b.set(a,new g(a)),this.controller_.addObserver(this),this.controller_.refresh())}};n.prototype.unobserve=function(a){if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");
if("undefined"!==typeof Element&&Element instanceof Object){if(!(a instanceof f(a).Element))throw new TypeError('parameter 1 is not of type "Element".');var b=this.observations_;b.has(a)&&(b["delete"](a),b.size||this.controller_.removeObserver(this))}};n.prototype.disconnect=function(){this.clearActive();this.observations_.clear();this.controller_.removeObserver(this)};n.prototype.gatherActive=function(){var a=this;this.clearActive();this.observations_.forEach(function(b){b.isActive()&&a.activeObservations_.push(b)})};
n.prototype.broadcastActive=function(){if(this.hasActive()){var a=this.callbackCtx_,b=this.activeObservations_.map(function(a){return new v(a.target,a.broadcastRect())});this.callback_.call(a,b,a);this.clearActive()}};n.prototype.clearActive=function(){this.activeObservations_.splice(0)};n.prototype.hasActive=function(){return 0<this.activeObservations_.length};var y="undefined"!==typeof WeakMap?new WeakMap:new m,t=function(a){if(!(this instanceof t))throw new TypeError("Cannot call a class as a function.");
if(!arguments.length)throw new TypeError("1 argument required, but only 0 present.");var b=c.getInstance();b=new n(a,b,this);y.set(this,b)};["observe","unobserve","disconnect"].forEach(function(a){t.prototype[a]=function(){return(b=y.get(this))[a].apply(b,arguments);var b}});return"undefined"!==typeof r.ResizeObserver?r.ResizeObserver:r.ResizeObserver=t});
document.getElementsByClassName||(document.getElementsByClassName=function(e){return querySelectorAll("."+e)},Element.prototype.getElementsByClassName=document.getElementsByClassName);
!window.addEventListener&&function(e,m,u,r,w,q,b){e[r]=m[r]=u[r]=function(a,c){var d=this;b.unshift([d,a,c,function(a){a.currentTarget=d;a.preventDefault=function(){a.returnValue=!1};a.stopPropagation=function(){a.cancelBubble=!0};a.target=a.srcElement||d;c.call(d,a)}]);this.attachEvent("on"+a,b[0][3])};e[w]=m[w]=u[w]=function(a,c){for(var d=0,f;f=b[d];++d)if(f[0]==this&&f[1]==a&&f[2]==c)return this.detachEvent("on"+a,b.splice(d,1)[0][3])};e[q]=m[q]=u[q]=function(a){return this.fireEvent("on"+a.type,
a)}}(Window.prototype,HTMLDocument.prototype,Element.prototype,"addEventListener","removeEventListener","dispatchEvent",[]);NodeList.forEach||(NodeList.prototype.forEach=Array.prototype.forEach);Object.values||(Object.values=function(e){var m=[],u;for(u in e)e.hasOwnProperty(u)&&m.push(e[u]);return m});
"function"!=typeof CustomEvent&&(CustomEvent=function(e,m){m=m||{bubbles:!1,cancelable:!1,detail:null};var u=document.createEvent("CustomEvent");u.initCustomEvent(e,!!m.bubbles,!!m.cancelable,"undefined"==typeof m.detail?null:m.detail);return u});var NativendoNlpFeature=!0;
try{URL.prototype.normalize=function(){try{if(!/^https?:\/\/[^\/]/i.test(this.href))throw"Invalid URL";this.hash=this.password=this.username="";try{this.pathname=decodeURI(this.pathname)}catch(u){}this.hostname=this.hostname.replace(/\.$/,"");/^www\.(?:[a-z\-\d]{2,63})\.(?:[a-z.]{2,5})$/i.test(this.hostname)&&(this.hostname=this.hostname.replace(/^www\./i,""));this.pathname=this.pathname.replace(/\/\/+/g,"/");var e=[{pattern:"^utm_",flags:"i"},{pattern:"^pk_campaign$",flags:"i"},{pattern:"^pk_source$",
flags:"i"},{pattern:"^pk_medium$",flags:"i"},{pattern:"^pk_keyword$",flags:"i"},{pattern:"^pk_content$",flags:"i"},{pattern:"^pk_cid$",flags:"i"}],m=[];this.searchParams.forEach(function(u,r){e.every(function(e){return(new RegExp(e.pattern,e.flags)).test(r)?(m.push(r),!1):!0})});m.forEach(function(e){this.searchParams.delete(e)},this);this.searchParams.sort();return this.toString().replace(/^https?:\/\//i,"//").replace(/\/(\?.*?)?$/,"$1")}catch(u){NativendoNlpFeature=!1}return!1}}catch(e){NativendoNlpFeature=
!1}String.prototype.toKeywords=function(){for(var e=this.toLowerCase().replace(/[\r\n\t\u00a0\u2009]+/g," ").replace(/[.,\/\\#!$\u20ac%\^\u00b0&\*;:\{\}=_`~()\?"'\u2018-\u201f]/g,"").replace(/\s{2,}/g," ").trim().split(" "),m=[],u=0,r=e.length;u<r;u++)-1===m.indexOf(e[u])&&m.push(e[u]);return m.filter(function(e){return!(e.match(/^\d+$/g)||2>=e.length)}).sort()};var dummy=function(){};["log","debug","info","warn","error"].forEach(function(e){window[e]||(window[e]=dummy)});
(function(e,m,u,r){"undefined"==typeof nativendo_pc&&(nativendo_pc={});e.NativendoV2=function(r,q){var b=this;if("undefined"==typeof q){try{if(!r.endpoints||!r.identifier||!r.uniqueId)throw"Invalid configuration";}catch(a){console.log(a);return}b.endpoints=r.endpoints;b.identifier=r.identifier;b.uniqueId=r.uniqueId;b.options=r.options}try{if(b.currentUrl=e!==e.parent?e.top.location.href:e.location.href,!b.currentUrl)throw"location.href is undefined";}catch(a){b.currentUrl=m.referrer||e.location.href}b.gdpr=
1;b.gdprPd=null;b.gdprConsent="";"undefined"!=typeof e["nativendo_"+b.uniqueId+"_tcdata"]&&(b.gdpr=e["nativendo_"+b.uniqueId+"_tcdata"].gdpr,b.gdprPd=e["nativendo_"+b.uniqueId+"_tcdata"].gdprPd,b.gdprConsent=e["nativendo_"+b.uniqueId+"_tcdata"].gdprConsent);b.callback="function"==typeof r.callback?r.callback:function(){};b.trackMode="normal";b.hashRegex=/\-([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.([a-z0-9]+)\.?(preview|heatmap|clickmap|lineup|survey\-[0-9]+|story\-[0-9]+)?\.?(0|1)?$/i;b.hashParts=[];
b.plugins={};b.duplicateCheck={};b.multipleUseCheck={};b.bidRequest={id:null,imp:[],site:{page:b.currentUrl,ref:m.referrer},tmax:2040};b.bidImp={id:null,tagid:null,secure:"https:"===m.location.protocol?1:0,"native":{context:1,contextsubtype:11,plcmttype:1,privacy:0,assets:[{id:1,required:1,title:{len:90}},{id:2,required:1,img:{wmin:300,hmin:300,type:3}},{id:4,required:1,data:{type:1,len:70}},{id:5,required:1,data:{type:2,len:350}}]},ext:{iframe:e!==e.parent,position:1}};b.dspRequestFormats={otto:{v:"v5.13.0-pre",
pageUrl:b.currentUrl,bidId:"",auctionId:"",transactionId:"",adUnitCode:"example-ad",params:{accountId:"seedingall",placementId:"exampleorg_Native",bidfloor:.1},sizes:[],mediaTypes:{"native":{image:{required:!0},title:{required:!0,len:40},clickUrl:{required:!0},body:{required:!0}}},gdprConsent:{consentString:"",consentRequired:!0}}};b.nodeRefresh={};b.waitUntilRefresh=3;b.refresh=function(a,c,d,f){var e=new b.DOM,p=Object.keys(b.stack),g=Math.round((new Date).getTime()/1E3);"undefined"==typeof d&&
(d=!0);"undefined"==typeof c&&(c=!0);"undefined"==typeof f&&(f=!0);a||(a=[]);Array.isArray(a)||(a=[a]);0==a.length&&(a=Object.keys(b.stack.nodes));a.forEach(function(a){if(!(b.nodeRefresh[a]&&g-b.waitUntilRefresh<b.nodeRefresh[a].t)){b.nodeRefresh[a]={t:g,c:b.nodeRefresh[a]?b.nodeRefresh[a].c+1:1};var k=[];p.forEach(function(c){switch(c){case "campaigns":break;case "htmlElements":b.stack[c][a]&&b.stack[c][a].forEach(function(a){k.push(a)});default:delete b.stack[c][a]}});f&&delete b.trackedInventory[a];
delete b.passbackInventory[a];b.findNodes(a,function(){k.forEach(function(a){e.destroy(a)})},c,d)}})};b.autorefresh=function(a,c,d){d*=1E3;var f=new b.Visibility,e=function(e,g){return f.isInViewport(a)&&f.isVisibleByStyle(a)?.5<=f.percentage(a)&&(d-=200,0>=d)?(g&&clearInterval(g),b.refresh(c),!0):!1:!1};setTimeout(function(){e()||f.every(200,function(a,b){e(a,b)})},200)};b.getEndpoint=function(a){return b.endpoints[a||"c"]||!1};b.getIdentifier=function(){return b.identifier};b.stack={nodes:{},targets:{},
campaigns:{},impIds:{},htmlElements:{},creatives:{}};b.setTrackMode=function(a){b.trackMode=a};b.setHashParts=function(a){b.hashParts=a};b.reco=!1;b.blocked=!1;b.trackedInventory={};b.passbackInventory={};b.initiated=!1;b.searchInterval=!1;b.findNodesAndRender=function(){if(b.initiated)return!1;var a=new b.DOM;b.initiated=!0;b.findNodes();b.searchInterval=setInterval(b.findNodes,40);a.ready(function(){b.searchInterval&&(clearInterval(b.searchInterval),b.searchInterval=!1);b.searchInterval=setInterval(b.findNodes,
120);setTimeout(function(){b.searchInterval&&(clearInterval(b.searchInterval),b.searchInterval=!1);var a=e["nativendo_"+b.uniqueId+"_map"];if("undefined"!=typeof a&&null!=a){var d=!1;Object.keys(a.d).forEach(function(b){a.d[b].used||("undefined"===typeof a.d[b].es||a.d[b].es?d=!0:a.d[b].ll||(a.d[b].found=!0,a.d[b].used=!0))});d&&(b.searchInterval=setInterval(b.findNodes,400))}},2040)});return!0};b.executedUserMatching=!1;b.renderQueue=[];b.renderData={};b.renderTimeoutId=null;b.xpathAdUnits={};b.findNodes=
function(a,c,d,f){c="function"==typeof c?c:function(){};a=a?a:null;var k=new b.DOM,p=new b.Tracker,g=e["nativendo_"+b.uniqueId+"_map"],v=e["nativendo_"+b.uniqueId+"_conf"],n=0,y=0,t=0;if("undefined"!=typeof g&&null!=g){g.r&&(b.reco=!0);g.b&&(b.blocked=!0);try{Object.keys(g.d).forEach(function(c){a&&a!=c||g.d[c].x.forEach(function(a){b.xpathAdUnits[a]||(b.xpathAdUnits[a]={adUnitIds:[],adUnitId:null,renderedEventFired:!1});-1===b.xpathAdUnits[a].adUnitIds.indexOf(c)&&b.xpathAdUnits[a].adUnitIds.push(c)})}),
Object.keys(g.d).forEach(function(h){n++;g.d[h].found&&y++;g.d[h].used&&t++;a&&a!=h||g.d[h].x.forEach(function(a){var t=!0,n=!!g.d[h].or||f,y=null,E;-1!==a.indexOf("starts-with(")&&(E=k.findNode(a))&&E.id&&(a="#"+E.id);if(!n&&e.nativendo_pc.hasOwnProperty(a))t=!1,g.d[h].found=!0;else{if(y=k.findNode(a))g.d[h].found=!0;if(y===m.documentElement){e.nativendo_pc[a]=!0;return}}!1===d||b.trackedInventory.hasOwnProperty(h)||!y&&t||(g.d[h].ll?b.visibilityObserver.observedLazyLoadingInventoryIds&&b.visibilityObserver.observedLazyLoadingInventoryIds[h]||
(b.visibilityObserver.observedLazyLoadingInventoryIds=b.visibilityObserver.observedLazyLoadingInventoryIds||{},b.visibilityObserver.observedLazyLoadingInventoryIds[h]=b.visibilityObserver.observe(y,{checkIntersection:!0,unobserveOnVisibility:!0,intersectionObserverOptions:{rootMargin:v.lld+"px",threshold:0}},{visible:function(){b.trackedInventory[h]||"undefined"!==typeof g.d[h].ti&&!g.d[h].ti||(b.trackedInventory[h]=h,p.trackEvent({aid:h},b.blocked?["data/inventory","data/blocked"]:"data/inventory",
!1))},unobserve:function(){b.visibilityObserver.observedLazyLoadingInventoryIds&&b.visibilityObserver.observedLazyLoadingInventoryIds[h]&&delete b.visibilityObserver.observedLazyLoadingInventoryIds[h]}})):b.trackedInventory[h]||"undefined"!==typeof g.d[h].ti&&!g.d[h].ti||(b.trackedInventory[h]=h,setTimeout(function(){p.trackEvent({aid:h},b.blocked?["data/inventory","data/blocked"]:"data/inventory",!1)},400)));if(t&&null!==y&&(!g.d[h].used||f)){var q=function(a,d,h,g,t){if(e.nativendo_pc[t]&&!n)return!1;
if(d.ll)return b.visibilityObserver.observedLazyLoadingRenderIds&&b.visibilityObserver.observedLazyLoadingRenderIds[a]||(b.visibilityObserver.observedLazyLoadingRenderIds=b.visibilityObserver.observedLazyLoadingRenderIds||{},b.visibilityObserver.observedLazyLoadingRenderIds[a]=b.visibilityObserver.observe(h,{checkIntersection:!0,unobserveOnVisibility:!0,intersectionObserverOptions:{rootMargin:v.lld+"px",threshold:0}},{visible:function(){g.d[a].ll=!1;q(a,g.d[a],h,g,t);g.d[a].ll=!0},unobserve:function(){b.visibilityObserver.observedLazyLoadingRenderIds&&
b.visibilityObserver.observedLazyLoadingRenderIds[a]&&delete b.visibilityObserver.observedLazyLoadingRenderIds[a]}})),!0;if(("undefined"==typeof d.c.length||0<d.c.length||d.p)&&b.render({id:a,imp:d.id,rtb:d.rtb,bid:d.bid,campaigns:d.c,passback:d.p,target:h,nonce:g.n,xpath:t,group:d.g},f)&&(f=!1,c(),e.nativendo_pc[t]=!0,d.used=!0,d.ar))try{b.autorefresh(h,a,d.ar)}catch(K){}d.found&&!d.rendered&&(d.rendered=!0);try{if(d.rendered&&!b.xpathAdUnits[t].renderedEventFired){var k=!0;b.xpathAdUnits[t].adUnitIds.some(function(a){var c=
g.d[a];if(c.used)return b.xpathAdUnits[t].adUnitId=a,k=!0;c.rendered||(k=!1);return!1});if(k){var p=b.xpathAdUnits[t].adUnitId,m=p?g.d[p]:null,y=new CustomEvent("NativendoRendered",{detail:{adUnitIds:b.xpathAdUnits[t].adUnitIds,adUnitId:p,targetId:h.getAttribute("id"),target:h,xpath:t,filled:m&&m.used?!0:!1,passback:m&&m.used&&m.p&&("undefined"==typeof m.c.length||0==m.c.length)?!0:!1}});b.xpathAdUnits[t].renderedEventFired=!0;e.dispatchEvent(y)}}}catch(K){console.debug(K)}return!0},A=[];if(g.ob&&
g.ob[h]){var G=!1;g.ob[h].forEach(function(a){G||(g.d[h].g in b.multipleUseCheck&&g.mu.indexOf(a)?-1===b.multipleUseCheck[g.d[h].g].indexOf(a)&&(G=!0):b.stack.campaigns.hasOwnProperty(a)||(G=!0))});G&&(g.d[h].dsp=null)}if(g.dsp&&g.d[h].dsp){var r=function(c,f,d){var e=f=!1;try{if(c){var t=JSON.parse(c);switch(g.dsp[d].type){case "openrtb":t.seatbid&&t.seatbid.length&&t.seatbid[0].bid&&(t.bids=t.seatbid[0].bid);break;case "otto":var k=t[0];t={bids:[]};"undefined"!==typeof k&&(t.bids[0]={impid:k.requestId,
price:k.cpm,ext:{creative:{id:k.creativeId}},adm:{"native":{assets:[{id:1,requred:1,title:{text:k.native.title}},{id:2,required:1,img:k.native.image},{id:4,data:{value:"OTTO"}},{id:5,data:{type:2,value:k.native.body}}],link:{url:k.native.clickUrl,clicktrackers:k.native.clickTrackers},imptrackers:k.native.impressionTrackers}},adomain:["otto.de"]})}t&&0!==t.bids.length||(f=!0)}else f=!0}catch(K){f=!0}try{!b.executedUserMatching&&t.containerurl&&(b.executedUserMatching=!0,NativendoV2Loader.js(t.containerurl,
!0,{"data-container-config":JSON.stringify(t.containerconfig)}))}catch(K){}var p={price:"",ext:[]};if(!f){var n=function(a,b,c,d){a=a/c*d;c=Math.abs(b-Math.ceil(a));return 3<Math.abs(b-Math.floor(a))||3<c?!1:!0};t.bids.forEach(function(c){if(g.d[h].id==c.impid){if("string"==typeof c.adm)try{c.adm=JSON.parse(c.adm)}catch(Q){return}if(c.adm&&(c.adm.native&&(c.adm=c.adm.native),!(c.ext&&c.ext.creative&&c.ext.creative.id&&-1!==Object.values(b.stack.creatives).indexOf(c.ext.creative.id)))){var f=null;
c.ext&&c.ext.bidding_deal_id&&(f=c.ext.bidding_deal_id);if(!(null===f&&g.dsp&&g.dsp[d]&&g.dsp[d].deals_only||g.d[h].dsp[d]&&g.d[h].dsp[d].at&&1==g.d[h].dsp[d].at.length&&(-1<g.d[h].dsp[d].at.indexOf("private_deals")&&!f||-1<g.d[h].dsp[d].at.indexOf("open_auction")&&f))){if(g.d[h].ir.s){var t;null!==f&&g.dsp&&g.dsp[d]&&g.dsp[d].deal&&g.dsp[d].deal[c.ext.bidding_deal_id]&&(t=g.dsp[d].deal[c.ext.bidding_deal_id]);if(t&&!t.ci){var k=!0;c.adm.assets.some(function(a){if(!a.img)return!1;var b=!1;(b=a.img.w&&
a.img.h?n(a.img.w,a.img.h,g.d[h].ir.w,g.d[h].ir.h):t.sf.some(function(a){return n(g.d[h].ir.w,g.d[h].ir.h,a.w,a.h)}))||(k=!1);return!0});if(!k)return}}"length"in g.d[h].c&&0===g.d[h].c.length&&(g.d[h].c={});g.d[h].rtb=!0;g.d[h].dspName=d;g.d[h].bid=c;g.d[h].c.rtb=[c.impid+".0"];g.d[h].p=!1;f=q(h,g.d[h],y,g,a);e=!0;f&&(c.nurl&&NativendoV2Loader.js(c.nurl),p.price=c.price,p.ext=c.ext)}}}})}if(f||!e){if(g.d[h].ll&&f){g.d[h].dsp[d]=null;var m=!0;Object.keys(g.d[h].dsp).forEach(function(a){if(!m||g.d[h].dsp[a])m=
!1});m&&(g.d[h].dsp=null,g.d[h].used=!1)}q(h,g.d[h],y,g,a)}return p};if(g.d[h].dsp){var u=!1;Object.keys(g.d[h].dsp).forEach(function(a,c){g.d[h].dsp[a].rsp||"1"!=g.d[h].dsp[a].s2s||((new b.Tracker).trackAuction({aid:h,floor:g.d[h].dsp[a]["p:enc"],cpm:"",dsp:a}),delete g.d[h].dsp[a]);g.d[h].dsp[a]&&g.d[h].dsp[a].rsp&&!u&&(u=!0,g.d[h].used=!0,g.d[h].rtb=!1,c=r(g.d[h].dsp[a].rsp,200,a),(new b.Tracker).trackAuction({aid:h,floor:g.d[h].dsp[a]["p:enc"],cpm:c.price,ext:c.ext,dsp:a}))});if(u)return}Object.keys(g.dsp).forEach(function(a,
c){if(g.d[h].dsp&&g.d[h].dsp[a]&&g.d[h].dsp[a].tid&&!g.d[h].dsp[a].rsp){v.gdpr&&(b.bidRequest.regs={ext:{gdpr:b.gdpr}},b.bidRequest.user={ext:{consent:b.gdprConsent}});c=JSON.parse(JSON.stringify(b.bidRequest));c.id=g.id+"-r"+(b.nodeRefresh[h]?b.nodeRefresh[h].c:1)+"-s"+h;c.test=g.dsp[a].test;g.d[h].used=!0;g.d[h].rtb=!1;var f=JSON.parse(JSON.stringify(b.bidImp));f.id=g.d[h].id;f.tagid=g.d[h].dsp[a].tid;f.bidfloor=g.d[h].dsp[a]["p:enc"];f.native.plcmttype=g.d[h].ct;f.privacy=g.d[h].am?1:0;g.d[h].dsp[a]["p:raw"]&&
(g.d[h].dsp[a].enc?f.bidfloor_raw=g.d[h].dsp[a]["p:raw"]:f.bidfloor=g.d[h].dsp[a]["p:raw"]);f.native.assets[1].img.wmin=g.d[h].ir.w;f.native.assets[1].img.hmin=g.d[h].ir.h;"ow"in g.d[h].ir&&(f.native.assets[1].img.wmin=g.d[h].ir.ow,f.native.assets[1].img.hmin=g.d[h].ir.oh);c.imp.push(f);switch(g.dsp[a].type){case "openrtb":f.native={request:f.native};break;case "otto":var d=b.dspRequestFormats[g.dsp[a].type];d.bidId=g.d[h].id;d.transactionId=g.id;d.auctionId=g.id;d.params.bidfloor=g.d[h].dsp[a]["p:raw"];
d.params.placementId=g.d[h].dsp[a].tid;d.gdprConsent.consentRequired=!!c.regs.ext.gdpr;d.gdprConsent.consentString=c.user.ext.consent;f.native.assets.forEach(function(a){switch(!0){case "undefined"!==typeof a.title:d.mediaTypes.native.title.len=a.title.len;break;case a.data&&"undefined"!==typeof a.data.type&&2==a.data.type:d.mediaTypes.native.body.len=a.data.len;break;case a.img&&"undefined"!==typeof a.img.type&&3==a.img.type:d.mediaTypes.native.image.sizes=[a.img.wmin,a.img.hmin]}});c=d}A.push(NativendoV2Loader.request("POST",
g.dsp[a].endpoint.replace(/\[URL\]/g,(new b.URL).encode(b.currentUrl)),JSON.stringify(c),function(c,d){c=r(c,d,a);(new b.Tracker).trackAuction({aid:h,floor:f.bidfloor,cpm:c.price,ext:c.ext,dsp:a})},!0,2040,"application/json"))}});0<A.length&&Promise.all(A).then(function(){}).catch(function(a){})}0<A.length?setTimeout(function(){q(h,g.d[h],y,g,a)},g.tmax):q(h,g.d[h],y,g,a)}})})}catch(h){console.debug(h)}(y>=n||t>=n)&&b.searchInterval&&(clearInterval(b.searchInterval),b.searchInterval=!1)}};b.render=
function(a,c){var d=new b.DOM,f=!1,k=e["nativendo_"+b.uniqueId+"_map"];Object.keys(a.campaigns).forEach(function(c){a.rtb&&"rtb"!=c||!a.rtb&&"rtb"==c||a.campaigns[c].forEach(function(c){if(!b.stack.nodes.hasOwnProperty(a.id)){c=c.split(".");if(k.mu&&-1<k.mu.indexOf(c[0])){b.multipleUseCheck[a.group]||(b.multipleUseCheck[a.group]=[]);if(-1<b.multipleUseCheck[a.group].indexOf(c[0]))return;b.multipleUseCheck[a.group].push(c[0])}else if(b.stack.campaigns.hasOwnProperty(c[0]))return;if(a.group&&k.dc&&
k.dc[c[0]]){b.duplicateCheck[a.group]||(b.duplicateCheck[a.group]=[]);for(var d=0,e=k.dc[c[0]].length;d<e;d++)if(-1===b.duplicateCheck[a.group].indexOf(k.dc[c[0]][d]))b.duplicateCheck[a.group].push(k.dc[c[0]][d]);else return}f=!0;b.stack.nodes[a.id]=a.nonce+"/"+a.id+"/"+c[0]+"/"+c[1]+"/"+(a.rtb?"1":"0");b.stack.targets[a.id]=a.target;b.stack.impIds[a.id]=a.imp;b.stack.campaigns[c[0]]={nodeId:a.id,cti:c[1]};a.bid&&(a.bid.ext&&a.bid.ext.creative&&a.bid.ext.creative.id&&(b.stack.creatives[a.id]=a.bid.ext.creative.id),
b.stack.nodes[a.id]+="/"+(a.bid.adm&&a.bid.adm.link&&-1<a.bid.adm.link.url.indexOf("rtb-adin")?"in":"out"));b.renderTeaser(b.stack.nodes[a.id]);b.nodeRefresh[a.id]={t:Math.round((new Date).getTime()/1E3),c:b.nodeRefresh[a.id]?b.nodeRefresh[a.id].c:0}}})});if(c&&!f)return Object.keys(b.stack.campaigns).forEach(function(c){a.id==b.stack.campaigns[c].nodeId&&delete b.stack.campaigns[c]}),b.render(a,!1);b.passbackInventory.hasOwnProperty(a.id)||b.stack.nodes.hasOwnProperty(a.id)||!a.passback||(b.passbackInventory[a.id]=
a.id,d.insertAndExecute(a.target,a.passback),f=!0);return f};b.renderTeaser=function(a){a=a.split("/").slice(1);b.renderQueue.push(a);a=a[0];var c=b.stack.targets[a]||null;if(c){var d={},f=/^data\-nativendo\-(.+)$/;Object.keys(c.attributes).forEach(function(a){a=c.attributes[a];var b=a.nodeName.match(f);b&&"undefined"!=typeof b[1]&&(d[b[1]]=a.nodeValue)});0<Object.keys(d).length&&(b.renderData[a]=d)}b.renderTimeoutId||(b.renderTimeoutId=e.setTimeout(function(){var a=[],c=new e.nativendo[b.uniqueId].URL,
f=e["nativendo_"+b.uniqueId+"_conf"],d=[];d.push("rid="+c.encode(e["nativendo_"+b.uniqueId+"_map"].id));d.push("url="+c.encode(e.nativendo[b.uniqueId].currentUrl));e!==e.parent&&d.push("if=1");"undefined"!==typeof e.context&&"AMP-AD"==e.context.tagName&&d.push("amp=1");f.gdpr&&(d.push("gdpr="+e.nativendo[b.uniqueId].gdpr),d.push("gdpr_pd="+e.nativendo[b.uniqueId].gdprPd),d.push("gdpr_consent="+e.nativendo[b.uniqueId].gdprConsent));for(c=function(a){var c=[];a.forEach(function(d,f){var h=d[0],e=b.renderData[h]||
{};Object.keys(e).forEach(function(a){c.push("data["+h+"]["+a+"]="+e[a])});a[f]=d.join(".")});var f=[d.join("&")];0<c.length&&f.push(c.join("&"));NativendoV2Loader.request("POST",b.getEndpoint("d")+"/cds/delivery/renders/"+a.join("-")+"/",f.join("&"),function(a,b){try{eval(a)}catch(B){}},!0,1E4)};0<b.renderQueue.length;)a.push(b.renderQueue.pop()),10<=a.length&&(c(a),a=[]);b.renderTimeoutId=null;0<a.length&&c(a)},16))};b.teaser=function(a,c){c="undefined"==typeof c?!0:c;var d=e["nativendo_"+b.uniqueId+
"_map"];if(!c||b.stack.nodes.hasOwnProperty(a.id)){var f=function(d){var f=new b.DOM,h=new b.Observer;d=d||{};var g=e["nativendo_"+b.uniqueId+"_conf"],k=g.p;if(k.etr&&"object"==typeof k.etr)try{Object.keys(k.etr).forEach(function(b){a.etr||(a.etr={});a.etr[b]||(a.etr[b]=[]);k.etr[b].forEach(function(c){a.etr[b].push(c)})})}catch(F){console.debug(F)}var p=f.fromHTML(a.teaser),n=p.length;-1<["bottom","before","clear_inside"].indexOf(a.position)&&(p=[].slice.call(p,0).reverse());for(var y=0,v=n-1;y<
n;y++)(function(e){v--;1===e.nodeType&&("SCRIPT"===e.tagName?f.insertAndExecute(m.createElement("div"),e.outerHTML):(b.stack.htmlElements[a.id]=b.stack.htmlElements[a.id]||[],b.stack.htmlElements[a.id].push(e),f[a.position](e,c?b.stack.targets[a.id]:m.getElementById(a.target),"preview"==a.tm&&a.por),"clear_inside"===a.position&&(a.position="bottom"),"auto"==a.linking&&(e.style.cursor="pointer"),h.attach(a,e,d)))})(p[v]);-1<a.teaser.indexOf("nat-survey-ad")&&("undefined"==typeof b.plugins["survey-ad"]?
(b.plugins["survey-ad"]=null,NativendoV2Loader.js(b.endpoints.c+g.path.js+"plugins/survey-ad.js"+g.cq,!0,{"data-nati-plugin":"survey-ad"})):b.plugins["survey-ad"]&&b.plugins["survey-ad"].init());try{if(e!==e.parent){var A=m.getElementsByTagName("img"),q=0,r=function(){try{var a=e["nativendo_"+b.uniqueId+"_conf"].p.pmp||{};a.height=m.getElementsByTagName("body")[0].scrollHeight;e.top.postMessage(JSON.stringify(a),"*")}catch(P){}},w=setInterval(function(){800<=q&&clearInterval(w);r();++q},8);i=0;for(n=
A.length;i<n;i++)A.onload=r;r()}}catch(F){console.debug(F)}if(b.stack.htmlElements[a.id]){a.css&&[].slice.call(f.fromHTML(a.css)).forEach(function(a){if(1===a.nodeType){if(-1<(" "+a.className+" ").replace(/[\n\t]/g," ").indexOf(" nativendo-render-hook ")){if(b.renderCssHookAdded)return;b.renderCssHookAdded=!0}f.bottom(a,u)}});a.js&&f.insertAndExecute(m.createElement("div"),a.js);try{if(a.truncate=!0,a.truncate){var H=b.stack.htmlElements[a.id][0].parentNode;-1!==["before","after"].indexOf(a.position)&&
(H=H.parentNode);var N=[].slice.call(H.querySelectorAll(".nativendo-truncate-container")),O=[].slice.call(H.querySelectorAll("img"));N.forEach(function(a){var c=a.querySelector(".nativendo-truncate-text");b.ellipsis.truncateOnLoad(a,c,O,!1,16)})}}catch(F){console.debug(F)}try{Object.keys(a.plugins).forEach(function(c){a.plugins[c].forEach(function(f){if("js"==f)NativendoV2Loader[f](b.endpoints.c+g.path[f]+"plugins/"+c+"."+f+g.cq,!0,{"data-id":a.id+"."+a.lineItemId+"."+a.lineItemCreativeId,"data-plugin":b.uniqueId+
"."+c+"."+a.id});else NativendoV2Loader[f](b.endpoints.c+g.path[f]+"plugins/"+c+"."+f+g.cq)})})}catch(F){console.debug(F)}if(a.stc){var I=function(a,b,c){setTimeout(function(){var f=null;b.forEach(function(a){a.className=a.className.replace(/ nativendo-preview-highlight /,"",a.className);a=a.getBoundingClientRect();if(null===f||a.top<f)f=a.top});if(null!==f){var d=Math.round(f+a.pageYOffset-150);0>d&&(d=0);a.scrollTo(0,d);c&&setTimeout(function(){a.pageYOffset<=d&&b.forEach(function(a){a.className+=
" nativendo-preview-highlight "})},10)}},10)},L=!1;try{e.top!==e&&e.frameElement&&(L=!0,"scrollRestoration"in e.top.history&&"auto"==e.top.history.scrollRestoration&&e.top.addEventListener("pageshow",function(a){I(e.top,[e.frameElement],!0)}),I(e.top,[e.frameElement],!0))}catch(F){}"scrollRestoration"in e.history&&"auto"==e.history.scrollRestoration&&e.addEventListener("pageshow",function(c){I(e,b.stack.htmlElements[a.id],!L)});I(e,b.stack.htmlElements[a.id],!L)}}};if(!1!==a.feed){var k=new b.Math,
p=a.feed,g="nativendo_jsonp_callback"+k.uuidCompact().replace(/-/g,""),v="unknown";switch(!0){case -1!=p.indexOf("twiago"):v="twiago";break;case -1!=p.indexOf("plista"):v="plista";break;case -1!=p.indexOf("flashtalking"):v="flashtalking"}e[g]=function(c){var d={};try{if(c.assets)c.assets.forEach(function(a){a.title?d.title=a.title.text:a.link?d.url=a.link.url:a.data&&"2"==a.data.type?d.text=a.data.value:a.img&&"3"==a.img.type&&(d.img=a.img.url)}),c.eventtrackers&&c.eventtrackers.forEach(function(c){"1"==
c.method&&"1"==c.event&&(d.title=d.title+'<img src="'+c.url+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />');"2"==c.method&&"1"==c.event&&(a.teaser=a.teaser+'<script src="'+c.url+'">\x3c/script>')});else if(c.creatives){var h={headline:"title",text:"text",image_4x3:"img",clickurl:"url",linktext:"readmore",url:"url"};for(e in h)d[h[e]]||"undefined"===typeof c.creatives[0][e]||(d[h[e]]=c.creatives[0][e]);for(h=0;1>=h;h++)if(d.title=d.title+'<img src="'+c.creatives[h].viewtracking+
'" style="position:absolute;visibility:hidden;width:1px;height:1px" />',c.creatives[h].pixels){var e=0;for(var g=c.creatives[h].pixels.length;e<g;e++)d.title=d.title+'<img src="'+c.creatives[h].pixels[e]+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />'}}else d=c[0],"twiago"==v&&NativendoV2Loader.pixel(b.getEndpoint("t")+"/cds/track/log/?type=feed&msg=twiago-no-creatives")}catch(J){"twiago"==v&&NativendoV2Loader.pixel(b.getEndpoint("t")+"/cds/track/log/?type=feed&msg=twiago-creatives-error");
return}try{for(var k in d)d.hasOwnProperty(k)&&("img"==k&&-1==d[k].indexOf("?")&&(d[k]+="?"),a.teaser=a.teaser.replace(new RegExp("{"+k+"}","ig"),d[k]));a.url=d.url;f()}catch(J){}};var n=p.replace(/\{random\}|\[FT_RANDOM\]/g,k.uuidCompact()).replace(/\{url\}/g,encodeURIComponent(e.nativendo[b.uniqueId].currentUrl));"twiago"==v&&(n=n.replace(/\{gdpr\}/gi,e.nativendo[b.uniqueId].gdpr).replace(/\{gdpr_pd\}/gi,e.nativendo[b.uniqueId].gdprPd).replace(/\{gdpr_consent\}/gi,e.nativendo[b.uniqueId].gdprConsent).replace(/(\?|\&)callback=\{callback\}/gi,
""),NativendoV2Loader.request("GET",n,"",function(a,c){a&&"200"==c||NativendoV2Loader.pixel(b.getEndpoint("t")+"/cds/track/log/?type=feed&msg="+encodeURIComponent(JSON.stringify({s:c,u:n,r:a})));e[g](JSON.parse(a))},!0,5E3));v.match(/plista|flashtalking/)&&(n=n.replace(/\{callback\}/g,g),NativendoV2Loader.js(n))}else if(a.uca)try{d.d[a.id].id==a.impid&&function(){var c=d.d[a.id].bid,g=c.adm,h={title:"",text:"",img:"",readmore:"",sponsored:"",url:g.link.url,privacy_icon:""};g.assets.forEach(function(c){if(c.title)h.title=
c.title.text;else if(c.img){c={url:c.img.url,width:d.d[a.id].ir.w,height:d.d[a.id].ir.h,transform:"fit"};var f=/{img}([^"' ,]+)/i;if((f=a.teaser.match(f))&&f[1]){f=f[1].split("&");for(var e=[],g=0;g<f.length;g++)if(""!==f[g]){var k=f[g].split("=");c[k[0]]=k[1];if("height"===k[0]||"width"===k[0])e.push(k[0]),c[k[0]]=parseInt(c[k[0]])}f=/{img}([^"' ,]+)/ig;a.teaser=a.teaser.replace(f,"{img}");1===e.length&&(f=d.d[a.id].ir.w/d.d[a.id].ir.h,"height"===e[0]?c.width=c.height*f:c.height=c.width/f)}switch(d.dsp[d.d[a.id].dspName].type){case "otto":c.mode=
"sc"}h.img=b.getEndpoint("c")+"/cdn/asset/image?"+(new b.URL).toQueryString(c)}else if(c.data)switch(c.id){case 4:case "4":h.sponsored=c.data.value;break;case 5:case "5":h.text=c.data.value}});g.privacy&&(h.privacy_icon='<a href="'+g.privacy+'" class="nativendo-oba-icon" target="_blank"><img src="'+b.getEndpoint("c")+'/cdn/asset/img/oba-icon.png"></a>');var k={bidid:c.id?c.id:"",cpm:c.price,rtb:1,dsp:d.d[a.id].dspName,sponsored:h.sponsored,ext:c.ext?c.ext:""},p=Array.isArray(g.link.clicktrackers)?
g.link.clicktrackers:[];if(-1<h.url.indexOf("rtb-adin")){if(!d.u||!d.u.match(/^https?:/))throw"No article url";var n=b.getEndpoint("d").replace(/^https?:\/\//,"").replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&"),v=(n=(new RegExp("^(.*?)(https?(?:://|(?:[%A-F0-9])+2F)(?:"+n+")(?:/|(?:[%A-F0-9])+2F)(?:d|cds(?:/|(?:[%A-F0-9])+2F)delivery)(?:/|(?:[%A-F0-9])+2F)rtb-adin(?:/|(?:[%A-F0-9])+2F)(?:cid(?:/|(?:[%A-F0-9])+2F)|)([a-z0-9]+))","g")).exec(h.url))?!!n[1]:!1;if(!n)throw"no valid cid in bid.adm";var q=n[3],
r=[b.uniqueId,a.id,q,"0"];a.url=d.u+"#/"+h.title.replace(/<\/?[^>]+(>|$)/g,"").replace(/[ .,!?]/g,"-").replace(/[^a-zA-Z0-9-_]/g,"").toLowerCase()+"-"+r.join(".");a.rtbcid=q;a.out=!1;v&&(0===h.url.indexOf("https://googleads.g.doubleclick.net/dbm/clk")?p.push('<iframe src="'+h.url+'" style="position:absolute;height:1px;width:1px;visibility:hidden;"></iframe>'):a.url=h.url.replace(n[2],encodeURIComponent(a.url)));h.url=a.url}else 0<a.url.indexOf("{url}")?(h.url=e.encodeURIComponent(h.url)+"&"+(new b.URL).toQueryString(k),
a.url=a.url.replace("{url}",h.url)):a.url=h.url;0<p.length&&(a.etr||(a.etr={click:[]}),p.forEach(function(b){0<b.indexOf("${AUCTION_PRICE}")&&(b=b.replace("${AUCTION_PRICE}",c.price));a.etr.click.push(b)}));Array.isArray(g.imptrackers)&&g.imptrackers.forEach(function(a){0<a.indexOf("${AUCTION_PRICE}")&&(a=a.replace("${AUCTION_PRICE}",c.price));h.title=h.title+'<img src="'+a+'" style="position:absolute;visibility:hidden;width:1px;height:1px" />'});g.jstracker&&setTimeout(function(){(new b.DOM).insertAndExecute(m.createElement("div"),
g.jstracker)},50);for(var A in h)h.hasOwnProperty(A)&&(a.teaser=a.teaser.replace(new RegExp("{"+A+"}","ig"),function(a){return this.replace}.bind({replace:h[A]})));f(k)}()}catch(y){console.debug(y)}else f()}};b.video=function(a){b.modal(a)};b.prospect=function(a){b.modal(a)};b.modal=function(a){var c=new b.DOM,d=new b.Tracker,f=new b.Visibility,k=c.fromHTML(a.html)[0],p=k.getElementsByClassName("nativendo-close")[0],g=0,m=!0,n=e.top?e.top:e,q=n.document,t=n.document.getElementsByTagName("body")[0]||
n.document.body,h=800;"max_modal_size"in e["nativendo_"+b.uniqueId+"_vars"]&&(h=e["nativendo_"+b.uniqueId+"_vars"].max_modal_size);"modal_css_hook"in e["nativendo_"+b.uniqueId+"_vars"]&&[].slice.call(c.fromHTML(e["nativendo_"+b.uniqueId+"_vars"].modal_css_hook)).forEach(function(a){1===a.nodeType&&c.bottom(a,k)});p.addEventListener("click",function(){c.destroy(k);m=!1},!1);b.modalSH=screen.availHeight;b.modalCoords=null;c.bottom(k,t);var r=function(a,f){var d=a.getElementsByClassName("nativendo-content")[0];
if(d&&(!f||b.modalSH!==screen.availHeight)){!d.getAttribute("data-style")&&d.setAttribute("data-style",d.getAttribute("style")?d.getAttribute("style"):"");!a.getAttribute("data-style")&&a.setAttribute("data-style",a.getAttribute("style")?a.getAttribute("style"):"");d.style.maxHeight="none";b.modalCoords||(a.style.width="auto",d.style.width||(d.style.width="auto"),b.modalCoords=c.getOffsetRect(d));a.style.display="none";var e=n.innerHeight&&(n.innerHeight-50<b.modalCoords.height||b.modalCoords.width>
n.innerWidth);(" "+a.className+" ").match(/ nativendo\-(video|responsive)\-modal /g)&&(e=!1);if(e){var g=d.style,k=q.documentElement;a.style.position="absolute";g.position="absolute";g.top=(n.pageYOffset||q.scrollTop)-(q.clientTop||0)+"px";g.left=(n.pageXOffset||q.scrollLeft)-(q.clientLeft||0)+"px";g.width=(b.modalCoords.width<=n.innerWidth?n.innerWidth:b.modalCoords.width)+"px";g.marginBottom="0px";n.innerWidth>h&&(g.width=h+"px",g.left=(""!=g.left?parseInt(g.left):0)+(n.innerWidth/2-h/2)+"px");
a.style.width=Math.max(t.scrollWidth,t.offsetWidth,k.clientWidth,k.scrollWidth,k.offsetWidth)+"px";a.style.height=Math.max(t.scrollHeight,t.offsetHeight,k.clientHeight,k.scrollHeight,k.offsetHeight)+"px";b.modalCoords.width>parseInt(a.style.width)&&(g=g.left?parseInt(g.left):0,a.style.width=b.modalCoords.width+g+"px");f&&(b.modalSH=screen.availHeight)}e||(a.setAttribute("style",a.getAttribute("data-style")),d.setAttribute("style",d.getAttribute("data-style")));a.style.display="block"}};b.modalResize||
n.addEventListener("resize",function(){var a=q.getElementsByClassName("nativendo-modal")[0];a&&a.parentNode&&r(a,!0)},!0);b.modalResize=!0;r(k,!1);var B=k.getElementsByTagName("iframe");B.length&&f.every(100,function(a,c){for(a=0;a<B.length;a++)B[a]&&B[a].contentWindow||c&&clearInterval(c),f.isInViewport(B[a])&&f.isVisibleByStyle(B[a])&&1<=f.percentage(B[a])?B[a].contentWindow&&B[a].contentWindow.postMessage({nat_visible:!0},"*"):B[a].contentWindow&&B[a].contentWindow.postMessage({nat_visible:!1},
"*")});var C={noc:a.noc,aid:a.aid,cid:a.cid,cti:a.cti,sess:a.sess,ti:0};p=function(a){if(this.href){var c={u:this.href},b;for(b in C)c[b]=C[b];try{a.which&&a.type&&"mousedown"==a.type?2==a.which&&d.trackEvent(c,"content/clickout",!1):d.trackEvent(c,"content/clickout",!1)}catch(S){}}};for(var u=k.getElementsByTagName("a"),D=0,w=u.length;D<w;D++)if(-1==u[D].className.indexOf("nativendo-social")&&("#"!=u[D].href.charAt(0)&&0!==u[D].href.indexOf("mailto:")&&(u[D].target="_blank"),!(u[D].hasAttribute("href")&&
0==u[D].getAttribute("href").indexOf("#")||-1<u[D].href.replace(/^https?/,"").indexOf(a.article_url.replace(/^https?|\/$/g,""))))){u[D].addEventListener("click",p,!1);try{u[D].addEventListener("dblclick",p,!1),u[D].addEventListener("mousedown",p,!1)}catch(A){}}"content"==a.type&&a.track_show_and_dwell&&(d.trackEvent(C,"content/show",!0),f.every(1E3,function(c,b){g=Math.round(c/1E3);if(!m||120<g)try{clearInterval(b)}catch(R){}else 0<g&&0===g%3&&(C.ti=g,d.trackEvent(C,a.type+"/dwell",!1))}))};b.getTargets=
function(a,c,b){for(var d=!1,e={},p=0,g=c.length;p<g;p++){fixedLegacy=!1;try{for(var q=c[p].replace(/^.*(%.+?%).*$/,"$1"),n=m.evaluate(c[p],m,null,XPathResult.ANY_TYPE,null),r=[];node=n.iterateNext();)r.push(node);r.forEach(function(c){switch(b[p]){case "nativendo-title":legacyContent=-1!==["TITLE","SCRIPT","STYLE"].indexOf(c.tagName)&&a.data.clean_title?a.data.clean_title:a.data.title;break;case "nativendo-article":legacyContent=a.data.article}c.innerHTML=c.innerHTML.replace(new RegExp(q,"ig"),legacyContent);
fixedLegacy||-1!==["TITLE","SCRIPT","STYLE"].indexOf(c.tagName)||(c.id=b[p],fixedLegacy=!0)})}catch(h){}}try{for(var t in a.data)if(a.data[t])try{if(target=m.getElementById("nativendo-"+t))d=!0,e[t]=target}catch(h){}}catch(h){return!1}return d?e:d};b.content=function(a,c,d){var f=new b.DOM,k=new b.Observer,p=new b.Visibility,g=new b.Tracker,q=e["nativendo_"+b.uniqueId+"_conf"],n,r=[],t=[];a.pre_js&&f.insertAndExecute(m.createElement("div"),a.pre_js);var h=b.getTargets(a,c,d);c.forEach(function(a){t.push(a.replace(/^.*(%.+?%).*$/,
"$1"))});var E=function(c){function d(a,c){var b;a=[].slice.call(a.getElementsByClassName("nativendo-marker"));var d={};["noc","cid","aid","sess"].forEach(function(a){d[a]=c[a]});d.mid=[];a.forEach(function(a){var f={};["noc","cid","aid","sess"].forEach(function(a){f[a]=c[a]});try{if(b=JSON.parse(a.getAttribute("data-nativendo-custom-event")))if(f.mid=b.key,d.mid.push(b.key),"visibility"==b.type){var e=function(c,b){if(!p.isInViewport(a))return!1;b&&clearInterval(b);g.trackEvent(f,"marker/watch",
!1);return!0};setTimeout(function(){e()||p.every(400,function(a,c){e(a,c)})},400)}}catch(I){}});0<d.mid.length&&g.trackEvent(d,"marker/view")}if(!c)return!1;try{a.data.clean_title&&(m.title=a.data.clean_title)}catch(A){}for(var h in a.data)if(a.data[h]){try{if(n=c[h])switch(h){case "image":case "intro":n.innerHTML=a.data[h];r.push(n);break;case "title":var v=-1!==["TITLE","SCRIPT","STYLE"].indexOf(n.tagName)&&a.data.clean_title?a.data.clean_title:a.data.title;t.forEach(function(a){n.innerHTML=n.innerHTML.replace(new RegExp(a,
"ig"),v)});-1===["TITLE","SCRIPT","STYLE"].indexOf(n.tagName)&&(n.innerHTML=v);break;case "article":var B=a.data[h]+a.css;q.options.acs?f.insertAndExecute(n,B):n.innerHTML=B;a.js&&f.insertAndExecute(m.createElement("div"),a.js);r.push(n);b.adjustElements(n);try{d(n,a)}catch(A){}}}catch(A){console.debug(A)}"teasers"==h&&(b.reco=!1,a.data[h].forEach(function(a){try{b.teaser(a,!1)}catch(G){console.debug(G)}}))}Object.keys(a.plugins).forEach(function(c){a.plugins[c].forEach(function(d){if("js"==d)NativendoV2Loader[d](b.endpoints.c+
q.path[d]+"plugins/"+c+"."+d+q.cq,!0,{"data-id":a.aid+"."+a.cid+"."+a.cti,"data-plugin":b.uniqueId+"."+c+"."+a.id});else NativendoV2Loader[d](b.endpoints.c+q.path[d]+"plugins/"+c+"."+d+q.cq)})});k.monitor(a,r);e.addEventListener("message",function(a){try{var c=a.data.split(":");if("ifr"==c[0]&&"height"==c[1])for(var b=m.getElementsByTagName("iframe"),d=0;d<b.length;d++)if(b[d].contentWindow===a.source){b[d].height=c[2];break}}catch(H){}},!1);if("heatmap"==b.trackMode)try{setTimeout(function(){e.parent.postMessage('{"height": '+
m.getElementsByTagName("body")[0].scrollHeight+"}",m.referrer)},1E3)}catch(A){console.debug(A)}};!1!==h?E(h):f.ready(function(){E(b.getTargets(a,c,d))})};b.adjustElements=function(a){var c,b,f;["img","video"].forEach(function(d){f=a.getElementsByTagName(d);c=0;for(b=f.length;c<b;c++)if("img"!==d||""!=f[c].src)try{f[c].style.height="auto",f[c].style.width?(f[c].style.maxWidth=f[c].style.width,f[c].style.width="100%"):f[c].width&&(f[c].style.maxWidth=f[c].width+"px",f[c].style.width="100%")}catch(p){console.debug(p)}})};
b.Date=function(){};b.Date.prototype={getTimestamp:function(){return Math.round((new Date).getTime()/1E3)}};b.NLP=function(){};b.NLP.prototype={getItemPropData:function(a){var c=["headline","alternativeHeadline","articleBody"],b={};z=0;for(li=c.length;z<li;z++){b[c[z]]=[];var f=a.querySelectorAll('*[itemprop="'+c[z]+'"]');i=0;for(l=f.length;i<l;i++)if(""!=f[i].innerText.replace(/[\n\s\t]/,"")&&void 0!=f[i].innerText&&"SCRIPT"!=f[i].tagName&&"STYLE"!=f[i].tagName&&"A"!=f[i].tagName)for(tmp=f[i].innerText.replace(/\n\n+/g,
"\n").replace(/ [ ]+/g,"s").split("\n"),x=0,tl=tmp.length;x<tl;x++)tmp[x]=tmp[x].replace(/^\s+/g,"").replace(/\s+$/g,""),""!=tmp[x]&&b[c[z]].push(tmp[x])}return b},getBodyText:function(a){return(a.getElementsByTagName("body")[0]||a.body).innerText.trim()},categorize:function(a,c,b){try{if(b=(new URL(b)).normalize(),!b)return!1}catch(f){return!1}NativendoV2Loader.request("POST",a+"/check-url",(new URLSearchParams({url:b})).toString(),function(d,k){200==k&&"1"==d&&(NativendoV2Nlp=e.NativendoV2Nlp||
{url:b,processResults:function(d){d={url:b,website_id:c,text:d.articleText,meta_categories:d.metaCategories.join(","),meta_keywords:d.metaKeywords.join(",")};NativendoV2Loader.request("POST",a+"/add-url",(new URLSearchParams(d)).toString(),function(a,c){},!0,5E3)}},NativendoV2Loader.js(r.endpoints.c+r.path.js+"nlp.js"+r.cq))},!0,5E3)}};b.DOM=function(){};b.DOM.prototype={getOffsetRect:function(a){a=a.getBoundingClientRect();var c=m.getElementsByTagName("body")[0],b=m.documentElement,f=c.getBoundingClientRect(),
k=b.getBoundingClientRect(),p=e.pageYOffset||b.scrollTop||c.scrollTop,g=e.pageXOffset||b.scrollLeft||c.scrollLeft,q=b.clientTop||c.clientTop||0;b=b.clientLeft||c.clientLeft||0;var n=0,r=0;"getComputedStyle"in e&&"relative"==e.getComputedStyle(c).position&&(n=f.top-k.top,r=f.left-k.left);return{top:Math.round(a.top+p-q-n),left:Math.round(a.left+g-b-r),width:a.width,height:a.height}},insertAndExecute:function(a,c){if(-1==c.indexOf("<"))try{Function('"use strict";'+c)()}catch(k){console.log("Passback failed with error: "+
k)}else{a.innerHTML=c;for(var b=Array.prototype.slice.call(a.getElementsByTagName("script")),f=0;f<b.length;f++)if(""!=b[f].src)a=m.createElement("script"),""!=b[f].innerHTML&&(a.onload=function(){try{eval(b[f].innerHTML)}catch(k){}}),a.src=b[f].src,m.getElementsByTagName("head")[0].appendChild(a);else try{eval(b[f].innerHTML)}catch(k){}}},ready:function(a){function c(){b||(b=!0,a())}var b=!1;try{var f=function(){return"complete"==m.readyState||"interactive"==m.readyState?(c(),!0):!1};if(!f()){if(m.onreadystatechange)var k=
m.onreadystatechange;m.onreadystatechange=function(){f();try{k&&k()}catch(n){}}}}catch(n){}if(m.addEventListener)m.addEventListener("DOMContentLoaded",c,!1);else if(m.attachEvent){try{var p=null!=e.frameElement}catch(n){}if(m.documentElement.doScroll&&!p){var g=function(){if(!b)try{m.documentElement.doScroll("left"),c()}catch(n){setTimeout(g,12)}};g()}m.attachEvent("onreadystatechange",function(){"complete"===m.readyState&&c()})}if(e.addEventListener)e.addEventListener("load",c,!1);else if(e.attachEvent)e.attachEvent("onload",
c);else{var q=e.onload;e.onload=function(){q&&q();c()}}},fromHTML:function(a){var c=m.createElement("div");c.innerHTML=a;return c.childNodes},createElement:function(a,c){a=m.createElement(a);for(var b in c)if(c.hasOwnProperty(b))if("innerHTML"==b||"innerText"==b)a[b]=c[b];else if("object"==typeof c[b])for(var f in c[b])c[b].hasOwnProperty(f)&&(a[b][f]=c[b][f]);else b.match(/on(load|error)/)?a[b]=c[b]:a.setAttribute(b,c[b]);return a},findNode:function(a){try{if(0<a.length&&"#"==a[0])return m.getElementById(a.substr(1));
var b=m.evaluate(a,m,null,XPathResult.ANY_TYPE,null).iterateNext()}catch(d){return null}return b?b:null},before:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,b);return a},after:function(a,b){var c=b.parentNode;c&&c.insertBefore(a,b.nextSibling);return a},bottom:function(a,b,d){d&&(b.innerHTML="");b.appendChild(a);return a},clear_inside:function(a,b,d){return this.bottom(a,b,!0)},top:function(a,b,d){d&&(b.innerHTML="");b.insertBefore(a,b.firstChild);return a},inside:function(a,b){b.insertBefore(a,
b.firstChild);return a},replace:function(a,b){a.parentNode.replaceChild(b,a);return b},destroy:function(a){return a.parentNode?(a.parentNode.removeChild(a),!0):a}};b.Event=function(a){this.params=a||{};this.set("ts",(new b.Date).getTimestamp())};b.Event.prototype={set:function(a,b){this.params[a]=b},get:function(a){return this.params.hasOwnProperty(a)?this.params[a]:null},getAll:function(){return this.params}};b.Math=function(){this.chars="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz".split("")};
b.Math.prototype={uuidCompact:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})}};b.externalTracker=function(a){if(0===a.indexOf("<")){var c=new b.DOM;[].slice.call(c.fromHTML(a)).forEach(function(a){"SCRIPT"===a.tagName?c.insertAndExecute(m.createElement("div"),a.outerHTML):c.bottom(a,m.getElementsByTagName("body")[0])})}else NativendoV2Loader.pixel(a)};b.Observer=function(){this.tra=new b.Tracker;this.vis=
new b.Visibility;this.dom=new b.DOM;this.evOpt={};this.tra.passiveSupported&&(this.evOpt.passive=!0)};b.Observer.prototype={attach:function(a,c,d){var f=this,k=d||{},p=["noc","aid","cid","cti"],g=a.id;b.reco&&(k.reco=1,k.ocid=b.hashParts[3]);"undefined"!==typeof a.target?p.forEach(function(b){k[b]=a[b]}):b.stack.nodes[g].split("/").forEach(function(a,b){p[b]&&(k[p[b]]=a)});b.stack.impIds[g]&&(k.imp=b.stack.impIds[g]);d.rtb&&(delete k.cid,a.rtbcid&&(k.cid=a.rtbcid));a.ll&&a.llit&&"visible"==a.llit||
f.tra.trackEvent(k,"ad/view");b.visibilityObserver.observe(c,{checkIntersection:!0,checkStyle:!0,checkFrameStyle:!0,unobserveOnVisibility:!0,intersectionObserverOptions:{rootMargin:"0px",threshold:.5},mutationObserverOptions:{attributes:!0,attributeFilter:["id","class","style","height"]}},{visible:function(){f.tra.trackEvent(k,a.ll&&a.llit&&"visible"==a.llit?["ad/view","ad/watch"]:"ad/watch");if(a.etr&&"object"==typeof a.etr.watch){for(var c=0,d=a.etr.watch.length;c<d;c++)b.externalTracker(a.etr.watch[c]);
a.etr.watch={}}}});if(c.getElementsByTagName("iframe").length){var q=c.getElementsByTagName("iframe")[0];f.vis.every(100,function(a,b){f.vis.isInViewport(q)&&f.vis.isVisibleByStyle(q)&&1<=f.vis.percentage(q)?q.contentWindow&&q.contentWindow.postMessage({nat_visible:!0},"*"):q.contentWindow&&q.contentWindow.postMessage({nat_visible:!1},"*")})}if(a.modal&&e.top!==e&&0!==a.url.indexOf("#"))try{e.top.document}catch(t){a.modal=!1,newTab=!0,a.out=!0}var n=function(c){var d=this,g=1==c.button||c.ctrlKey||
c.metaKey;if(!(1<c.button)){if(!d.href)return c.preventDefault(),!1;try{"undefined"==typeof a.etr&&(a.etr={click:[]});"[object String]"===Object.prototype.toString.call(a.etr.click)&&(a.etr.click=[a.etr.click]);d.hasAttribute("data-etr")&&(a.etr.click=[d.getAttribute("data-etr")]);for(var t=0,n=a.etr.click.length;t<n;t++)b.externalTracker(a.etr.click[t])}catch(J){}if(d.hasAttribute("data-prop"))try{k.properties=JSON.parse(d.getAttribute("data-prop"))}catch(J){}f.tra.trackEvent(k,"ad/click",!1,function(){if(!(a.out||
a.modal||g)){var b=a.url;d&&d.hasAttribute("data-href")&&(b=d.getAttribute("data-href"));""!=b&&setTimeout(function(){try{e.top.location.href?e.top.location.href=b:e.location.href=b}catch(D){e.location.href=b}},240)}});if(a.modal)return c.preventDefault(),0===m.getElementsByClassName("nativendo-modal").length&&NativendoV2Loader.js(a.modal_url),!1;if(!a.out&&!g)return c.preventDefault(),!1}};a.ct&&"redirect"==a.ct&&(n=function(){});if("auto"==a.linking)d=function(b){var c=f.dom.getOffsetRect(b.target),
d=function(a){a=a.target;"nativendo-dynamic-link"!=a.className&&(a=a.parentNode);a.parentNode.removeChild(a)};if(m.getElementById("vrm-quicknavigation")){b=f.dom.createElement("a",{"class":"nativendo-dynamic-link",href:a.url,innerHTML:"&nbsp;",target:a.out?"_blank":"_top",rel:"nofollow"});b.setAttribute("style","opacity:0.01;display:block;top:"+c.top+"px;left:"+c.left+"px;width:"+c.width+"px;height:"+c.height+"px;z-index:1400000;");try{b.style.setProperty("visibility","visible","important")}catch(C){}b.addEventListener("mouseout",
d,!1);b.addEventListener("touchend",d,!1);f.dom.inside(b,m.getElementsByTagName("body")[0])}else{var e=f.dom.createElement("div",{"class":"nativendo-dynamic-link"});b=f.dom.createElement("a",{href:a.url,innerHTML:"&nbsp;",target:a.out?"_blank":"_top",rel:"nofollow"});e.style.top=c.top+"px";e.style.left=c.left+"px";e.style.width=c.width+"px";e.style.height=c.height+"px";e.style.zIndex="1400000";try{e.style.setProperty("visibility","visible","important")}catch(C){}b.style.width=c.width+"px";b.style.height=
c.height+"px";f.dom.inside(b,e);f.dom.inside(e,m.getElementsByTagName("body")[0]);e.addEventListener("mouseout",d,!1);e.addEventListener("touchend",d,!1)}b.addEventListener("click",n,!1);b.addEventListener("auxclick",n,!1)},c.addEventListener("mouseover",d,!1),c.addEventListener("touchstart",d,this.evOpt);else{var r='a[href="'+a.url+'"]';a.urls&&1<a.urls.length&&(r=[],a.urls.forEach(function(a){r.push('a[href="'+a+'"]')}),r=r.join(","));d=[].slice.call(c.querySelectorAll(r));"A"===c.tagName&&(c.getAttribute("href")===
a.url||a.urls&&1<a.urls.length&&-1<a.urls.indexOf(c.getAttribute("href")))&&d.push(c);d.forEach(function(b){b.setAttribute("target",a.out?"_blank":"_top");if(!b.getAttribute("rel")||-1==b.getAttribute("rel").indexOf("nofollow")){var c=b.getAttribute("rel");b.setAttribute("rel",(null!==c?c+" ":"")+"nofollow")}a.urls&&1<a.urls.length&&!b.getAttribute("data-href")&&b.getAttribute("href")&&b.setAttribute("data-href",b.getAttribute("href"));b.addEventListener("click",n,!1);b.addEventListener("auxclick",
n,!1)})}},monitor:function(a,c){var d=this,f={noc:a.noc,aid:a.aid,cid:a.cid,cti:a.cti,sess:a.sess,ti:0};"preview"!=b.trackMode&&e.addEventListener("hashchange",function(){var a=e.location.hash.match(b.hashRegex);if(a&&b.uniqueId==a[1]){if(0<b.hashParts.length){var c=!1;[2,3,4,6].forEach(function(f){b.hashParts[f]!=a[f]&&(c=!0)});"lineup"!=b.hashParts[5]&&"lineup"!=a[5]||b.hashParts[5]==a[5]||(c=!0);c&&(e.scrollTo(0,0),e.location.reload())}a[5]&&0===a[5].indexOf("story-")&&(a[5]=null);b.setTrackMode(a[5]?
a[5]:"normal")}else e.location.hash&&(e.scrollTo(0,0),e.location.reload())});a.rtb&&(f.rtb=1);if(a.track_show_and_dwell){d.tra.trackEvent(f,a.type+"/show",!0);var k=0;d.vis.every(1E3,function(b,c){k=Math.round(b/1E3);if(k>=a.rti)try{clearInterval(c)}catch(C){}else 0<k&&0===k%3&&(f.ti=k,d.tra.trackEvent(f,a.type+"/dwell",!1))},a.hiddenCallback);e.addEventListener("beforeunload",function(){f.ti=k;d.tra.trackEvent(f,a.type+"/dwell",!1)},!1);if("content"===a.type){var p={0:!1,25:!1,50:!1,75:!1,100:!1},
g=1,q=0,n=function(){var b=m.getElementsByTagName("body")[0],c=m.documentElement,h=Math.max(b.scrollHeight,b.offsetHeight,c.clientHeight,c.scrollHeight,c.offsetHeight),k=e.innerHeight||c.clientHeight;b=b.scrollTop||c.scrollTop;h=0<b?Math.round((b+k)/h*100):0;if(!(q>h||(q=h,h=95<=h?100:75<=h?75:50<=h?50:25<=h?25:0,p[h]))){p[h]=!0;0<h&&!p[h-25]&&(g=0);h={scr:h,dec:g};for(var n in f)h[n]=f[n];d.tra.trackEvent(h,a.type+"/scroll",!1)}};e.addEventListener("scroll",n,this.evOpt);n();var r=function(b){if(this.href){var c=
{u:this.href};for(e in f)c[e]=f[e];var e=a.type+"/clickout";-1!=this.className.indexOf("nativendo-image-link")&&(e="image/click");try{b.which&&b.type&&"mousedown"==b.type?2==b.which&&d.tra.trackEvent(c,e,!1):d.tra.trackEvent(c,e,!1)}catch(J){}}};c.forEach(function(b){for(var c=b.getElementsByTagName("a"),e=0,g=c.length;e<g;e++)if(-1==c[e].className.indexOf("nativendo-social")&&("#"!=c[e].href.charAt(0)&&0!==c[e].href.indexOf("mailto:")&&(c[e].target="_blank"),!(c[e].hasAttribute("href")&&0==c[e].getAttribute("href").indexOf("#")||
-1<c[e].href.replace(/^https?/,"").indexOf(a.article_url.replace(/^https?|\/$/g,""))))){c[e].addEventListener("click",r,!1);try{c[e].addEventListener("dblclick",r,!1),c[e].addEventListener("mousedown",r,!1)}catch(M){}}c=b.getElementsByClassName("nativendo-image");var h=null;e=0;for(g=c.length;e<g;e++)c[e].addEventListener("load",function(){if("naturalWidth"in this&&1<this.naturalWidth)d.tra.trackEvent(f,"image/view",!1);else try{if(h=this.parentElement)"A"==h.nodeName&&"parentElement"in h&&(h=h.parentElement),
h.parentElement.removeChild(h)}catch(M){}});b.addEventListener("click",function(b){b={x:b.pageX,y:b.pageY,res:screen.availWidth+"x"+screen.availHeight};for(var c in f)b[c]=f[c];d.tra.trackEvent(b,a.type+"/click",!1)},!1)});c=m.getElementsByClassName("nativendo-social-link");n=["mail"];for(var t=0,h=c.length;t<h;t++)-1!==n.indexOf(c[t].getAttribute("data-rel"))&&c[t].addEventListener("click",function(){var a={u:this.href},b;for(b in f)a[b]=f[b];d.tra.trackEvent(a,"social/"+this.getAttribute("data-rel"),
!1)},!1)}}}};b.Tracker=function(){var a=this;this.fired={};this.passiveSupported=!1;try{var b=Object.defineProperty({},"passive",{get:function(){a.passiveSupported=!0}});e.addEventListener("test",null,b)}catch(d){}};b.Tracker.prototype={trackEvent:function(a,c,d,f){var k;b.hashParts[6]&&0==c.indexOf("content/")&&(a.sa=1);if("normal"!=b.trackMode)return"function"==typeof f&&f(!1),!1;d="undefined"==typeof d?!0:d;var p=[],g=this,q=!1;"string"==typeof c?p.push(c):p=c;d&&p.forEach(function(a){if(g.fired.hasOwnProperty(a))return q||
"function"!=typeof f||f(!1),q=!0,!1;g.fired[a]=!0});if(q)return!1;try{if(b.options.tracking&&b.options.tracking.custom){var n=b.options.tracking.custom,r=e["nativendo_"+b.uniqueId+"_conf"].p;for(k in n)n.hasOwnProperty(k)&&r[n[k]]&&(a[k]=r[n[k]])}}catch(h){}try{if(b.options.tracking&&b.options.tracking.props){d=!1;var t=a.properties||{};for(k in b.options.tracking.props)b.options.tracking.props.hasOwnProperty(k)&&(t[k]=b.options.tracking.props[k],d=!0);d&&(a.properties=t)}}catch(h){}a.t=c;try{a.aid&&
b.nodeRefresh&&b.nodeRefresh[a.aid]&&(a.ar=b.nodeRefresh[a.aid].c)}catch(h){}try{if(a.url=e!==e.parent?e.top.location.href:e.location.href,!a.url)throw"location.href is undefined";}catch(h){a.url=m.referrer||e.location.href}this.log(new b.Event(a),f)},trackAuction:function(a){var b=["rtb/auction","rtb/request"];a.da=1;a.cpm&&b.push("rtb/response");this.trackEvent(a,b,!1)},log:function(a,c){new b.DOM;var d=(new b.Math).uuidCompact();try{e["nativendo_"+b.uniqueId+"_map"].id&&(d=e["nativendo_"+b.uniqueId+
"_map"].id)}catch(f){}d=b.getEndpoint("t")+"/cds/tracking/event/"+d;a=(new b.URL).toQueryString(a.getAll());"function"!=typeof c&&(c=function(){});Promise.all([NativendoV2Loader.request("POST",d,a,function(a,b){},!0,3E4)]).then(function(){c(!0)}).catch(function(a){c(!1)})}};b.URL=function(){};b.URL.prototype={encode:function(a){return encodeURIComponent(a).replace(/[!'()*]/g,function(a){return"%"+a.charCodeAt(0).toString(16)})},toQueryString:function(a,b){var c=[],f;for(f in a)if(a.hasOwnProperty(f)){var e=
b?b+"["+f+"]":f,p=a[f];c.push("object"==typeof p?this.toQueryString(p,e):e+"="+this.encode(p))}return c.join("&")}};b.Visibility=function(){};b.Visibility.prototype={getHiddenProp:function(){if("hidden"in m)return"hidden";for(var a=["webkit","moz","ms","o"],b=0,d=a.length;b<d;b++)if(a[b]+"Hidden"in m)return a[b]+"Hidden";return!1},isHidden:function(a){"undefined"==typeof a&&(a=this.getHiddenProp());return a?m[a]:!1},checkByMove:function(a,c,d,f,k){var p=e;if(e.top!==e)try{e.top.document,p=e.top}catch(g){}p===
e&&e.IntersectionObserver?("undefined"===typeof b.checkOnMoveObserver&&(b.checkOnMoveObserver=new IntersectionObserver(function(a){a.forEach(function(a){a.isIntersecting&&"object"===typeof a.target.nativendoNodeUniqueKey&&a.target.nativendoNodeUniqueKey.forEach(function(c){b.checkOnMoveCallbacks[c]&&b.checkOnMoveCallbacks[c]()&&(b.checkOnMoveObserver.unobserve(a.target),delete b.checkOnMoveCallbacks[c])})})},{rootMargin:k+"px"}),b.checkOnMoveCallbacks={}),"undefined"===typeof a.nativendoNodeUniqueKey&&
(a.nativendoNodeUniqueKey=[]),a.nativendoNodeUniqueKey.push(c),b.checkOnMoveObserver.observe(a)):"undefined"===typeof b.checkOnMoveCallbacks&&(a=function(){p.clearTimeout(b.checkOnMoveId);b.checkOnMoveId=p.setTimeout(function(){Object.keys(b.checkOnMoveCallbacks).forEach(function(a){b.checkOnMoveCallbacks[a]()&&delete b.checkOnMoveCallbacks[a]})},25)},p!==e.top?this.every(200,function(a,c){Object.keys(b.checkOnMoveCallbacks).forEach(function(a){b.checkOnMoveCallbacks[a]()&&delete b.checkOnMoveCallbacks[a]});
0===Object.keys(b.checkOnMoveCallbacks).length&&(delete b.checkOnMoveCallbacks,e.clearInterval(c))}):(k={},f&&(k.passive=!0),p.addEventListener("scroll",a,k),p.addEventListener("resize",a,k),p.addEventListener("touchmove",a,k)),b.checkOnMoveCallbacks={});b.checkOnMoveCallbacks[c]=d},every:function(a,b,d){var c=this,e=0;var p=setInterval(function(){c.isHidden()||"function"==typeof d&&d()||b(++e*a,p)},a)},on:function(a,b){var c=visibilityTracker.getHiddenProp();if(!c)return!1;e.onbeforeunload=function(){"leave"==
a&&b()};m.addEventListener(c.replace(/[H|h]idden/,"")+"visibilitychange",function(){(visibilityTracker.isHidden()?"hidden":"visible")==a&&b()},!1);return!0},getCorrectElements:function(a){var b=e,d=m,f=!1;try{f=!!e.frameElement,e.frameElement&&e.top.document&&(a=e.frameElement,b=e.top,d=e.top.document)}catch(k){}return{win:b,doc:d,el:a,isFrame:f}},isVisibleByStyle:function(a){if(!a||!a.parentNode)return!1;a=e.getComputedStyle(a,null).getPropertyValue("visibility");return"hidden"===a||"collapse"===
a?!1:!0},isInViewport:function(a,b){var c=!1;if(!a)return!1;a=this.getCorrectElements(a);if(b&&!a.isFrame&&"none"==e.getComputedStyle(a.el).getPropertyValue("display")){var f=a.el.className;a.el.className+=" nativendo-visibility-check";c=!0}var k=a.el.getBoundingClientRect();if(!b&&(0>=k.width||0>=k.height))return!1;b=b||0;b=0<k.right&&k.left<(a.win.innerWidth||a.doc.documentElement.clientWidth)&&k.top-b<(a.win.innerHeight||a.doc.documentElement.clientHeight)&&0<k.bottom+b;c&&(a.el.className=f);return b},
percentage:function(a){if(!this.isInViewport(a)||!this.isVisibleByStyle(a))return 0;a=this.getCorrectElements(a);var b=a.el.getBoundingClientRect(),d=0,f=0;0<=b.top?d=Math.min(b.height,a.win.innerHeight-b.top):0<b.bottom&&(d=Math.min(a.win.innerHeight,b.bottom));0<=b.left?f=Math.min(b.width,a.win.innerWidth-b.left):0<b.right&&(f=Math.min(a.win.innerWidth,b.right));return d*f/(b.height*b.width)}};b.VisibilityObserver=function(a){this.options=a||{};this.observers={}};b.VisibilityObserver.prototype=
{observe:function(a,b,d){var c=this;if(a){b=b||{};d=d||{};var k=0;try{k=performance.now()}catch(n){k=Date.now()}var p=k.toString(36)+Math.random().toString(36);k=a.ownerDocument;var g=k.defaultView||k.parentWindow;c.observers[p]={options:b,callbacks:d,element:a,document:k,window:g};k.addEventListener&&"undefined"!=typeof k.onvisibilitychange||(b.checkDocument=!1);e.MutationObserver||(b.checkStyle=!1);e.IntersectionObserver||(b.checkIntersection=!1);b.requestAnimationFrameAvailable="function"==typeof e.requestAnimationFrame;
b.checkDocument&&(c.observers[p].documentObserver=function(){this.checkVisibilityByDocument(p);this.delayedExecuteCallback([a],p)}.bind(c),k.addEventListener("visibilitychange",c.observers[p].documentObserver),c.checkVisibilityByDocument(p));b.checkIntersection&&(c.observers[p].intersectionObserver=new IntersectionObserver(function(b,c){var d=this;b.forEach(function(a){d.observers[p].visibleByIntersection=a.isIntersecting});d.delayedExecuteCallback([a],p)}.bind(c),b.intersectionObserverOptions||{}),
c.observers[p].intersectionObserver.observe(a));if(b.checkStyle){if(b.checkParentStyle){c.observers[p].parentElements=[];d=[];for(var m=a;m.parentNode&&m.parentNode!==k;)d.push(m.parentNode),m=m.parentNode;c.observers[p].parentElements=d}b.checkFrameStyle&&g!==g.top&&g.frameElement&&(c.observers[p].frameElement=g.frameElement);c.observers[p].mutationObserver=new MutationObserver(function(a,b){var c=[];a.forEach(function(a){c.push(a.target)});this.delayedExecuteCallback(c,p)}.bind(c));c.getCheckElements(p).forEach(function(a){c.observers[p].mutationObserver.observe(a,
b.mutationObserverOptions||{})})}if("function"==typeof c.observers[p].callbacks.observe)try{c.observers[p].callbacks.observe(a,p)}catch(n){c.options.debug&&console.log(n)}c.delayedExecuteCallback([a],p);return p}},unobserve:function(a){if(this.observers[a]){var b=this.observers[a];b.documentObserver&&b.document.removeEventListener("visibilitychange",b.documentObserver);b.mutationObserver&&b.mutationObserver.disconnect();b.intersectionObserver&&b.intersectionObserver.disconnect();if("function"==typeof b.callbacks.unobserve)try{b.callbacks.unobserve(b.element,
a)}catch(d){this.options.debug&&console.log(d)}delete this.observers[a]}},disconnect:function(){var a=this;Object.keys(a.observers).forEach(function(b){a.unobserve(b)})},isVisible:function(a){if(this.observers[a]){a=this.observers[a];var b=a.options,d=!b.checkStyle||a.visibleByStyle,f=!b.checkIntersection||a.visibleByIntersection;return(!b.checkDocument||a.visibleByDocument)&&d&&f}},getCheckElements:function(a){if(this.observers[a]){a=this.observers[a];var b=a.options,d=[a.element];b.checkParentStyle&&
a.parentElements&&a.parentElements.forEach(function(a){d.push(a)});b.checkFrameStyle&&a.frameElement&&d.push(a.frameElement);return d}},checkVisibilityByDocument:function(a){this.observers[a]&&(a=this.observers[a],a.visibleByDocument="visible"==a.document.visibilityState)},checkElementVisibilityByStyle:function(a){"undefined"==typeof a.__nativendoVisibility__&&(a.__nativendoVisibility__={});var b=e.getComputedStyle(a);a.__nativendoVisibility__.visibleByStyle=!("hidden"==b.visibility||"collapse"==
b.visibility||"none"==b.display||"0px"==b.height)},checkVisibilityByStyle:function(a){var b=this;if(b.observers[a]){var d=b.observers[a];a=b.getCheckElements(a);d.visibleByStyle=a.every(function(a){"undefined"!=typeof a.__nativendoVisibility__&&"undefined"!=typeof a.__nativendoVisibility__.visibleByStyle||b.checkElementVisibilityByStyle(a);return a.__nativendoVisibility__.visibleByStyle?!0:!1})}},executeCallback:function(a){if(this.observers[a]){var b=this.observers[a],d=b.options;if(this.isVisible(a)){if("function"==
typeof b.callbacks.visible)try{b.callbacks.visible(b.element,a)}catch(f){this.options.debug&&console.log(f)}d.unobserveOnVisibility&&this.unobserve(a)}else if("function"==typeof b.callbacks.hidden)try{b.callbacks.hidden(b.element,a)}catch(f){this.options.debug&&console.log(f)}}},checkStyleAndExecuteCallback:function(a,b){var c=this;a.forEach(function(a){c.checkElementVisibilityByStyle(a)});c.checkVisibilityByStyle(b);c.executeCallback(b)},delayedExecuteCallback:function(a,b){var c=this;if(c.observers[b]){var f=
c.observers[b].options;f.checkStyle?f.requestAnimationFrameAvailable?e.requestAnimationFrame(function(){c.checkStyleAndExecuteCallback(a,b)}):c.checkStyleAndExecuteCallback(a,b):c.executeCallback(b)}}};b.Ellipsis=function(){var a=this;this.observer=e.ResizeObserver?new ResizeObserver(function(b,d){b.forEach(function(b){a.truncate(b.target.__nativendoContainer__,b.target.__nativendoContent__,b.target.__nativendoBreakWord__,b.target.__nativendoTimeout__)})}):null};b.Ellipsis.prototype={setOverflowingStyle:function(a){"undefined"==
typeof a.__nativendoTruncateCurrentHeight__&&(a.__nativendoTruncateCurrentHeight__=a.clientHeight);"undefined"==typeof a.__nativendoTruncateCurrentStyle__&&(a.__nativendoTruncateCurrentStyle__={overflow:a.style.overflow,"overflow-y":a.style["overflow-y"],"max-height":a.style["max-height"],height:a.style.height});a.style.setProperty("overflow-y","visible","important");a.style.setProperty("max-height","none","important");a.style.setProperty("height","auto","important")},unsetOverflowingStyle:function(a){if(a.__nativendoTruncateCurrentStyle__){var b=
a.__nativendoTruncateCurrentStyle__;a.style.setProperty("overflow-y",b["overflow-y"]);a.style.setProperty("max-height",b["max-height"]);a.style.setProperty("height",b.height)}delete a.__nativendoTruncateCurrentHeight__;delete a.__nativendoTruncateCurrentStyle__},isTextOverflowing:function(a){return a.__nativendoTruncateCurrentHeight__<a.clientHeight},executeTruncate:function(a,b,d){if(a){b=b||a;"undefined"==typeof b.__nativendoTruncateText__&&(b.__nativendoTruncateText__=b.textContent.replace(/[\r\n\t ]+/g,
" "));b.textContent=b.__nativendoTruncateText__;this.setOverflowingStyle(a);if(this.isTextOverflowing(a)){var c=b.textContent.length;d=d||!1;for(var e=0;this.isTextOverflowing(a)&&0<c&&1E3>e;)e++,wordDelimiterPos=b.textContent.lastIndexOf(" ",c-1-4),-1<wordDelimiterPos?c=wordDelimiterPos:c--,b.textContent=b.textContent.substring(0,c)+(0<c?" ...":"");if(d){for(e=0;!this.isTextOverflowing(a)&&1E3>e;)e++,c++,b.textContent=b.__nativendoTruncateText__.substring(0,c)+" ...";c--;b.textContent=b.textContent.substring(0,
c)+(0<c?" ...":"")}}this.unsetOverflowingStyle(a)}},truncate:function(a,b,d,e){var c=this;if(a)if(e){if(!a.__nativendoTruncateTimeoutId__){var f=setTimeout(function(){a.__nativendoTruncateTimeoutId__==f&&(a.__nativendoTruncateTimeoutId__=null,c.executeTruncate(a,b,d))},e);a.__nativendoTruncateTimeoutId__=f}}else c.executeTruncate(a,b,d)},truncateOnLoad:function(a,b,d,e,k){var c=this;a&&(b=b||a,doc=a.ownerDocument,win=doc.defaultView||doc.parentWindow,a.__nativendoContainer__=a,a.__nativendoContent__=
b,a.__nativendoBreakWord__=e,a.__nativendoTimeout__=k,b.__nativendoContainer__=a,b.__nativendoContent__=b,b.__nativendoBreakWord__=e,b.__nativendoTimeout__=k,win.addEventListener("load",function(){c.truncate(a,b,e,k)}),win.addEventListener("resize",function(){c.truncate(a,b,e,k)}),d.forEach(function(d){d.addEventListener("load",function(){c.truncate(a,b,e,k)});c.observer&&!d.__nativendoObserveResize__&&(d.__nativendoContainer__=a,d.__nativendoContent__=b,d.__nativendoBreakWord__=e,d.__nativendoTimeout__=
k,d.__nativendoObserveResize__=!0,c.observer.observe(d))}),c.observer&&!b.__nativendoObserveResize__&&(b.__nativendoObserveResize__=!0,c.observer.observe(b)),c.observer&&!a.__nativendoObserveResize__&&(a.__nativendoObserveResize__=!0,c.observer.observe(a)),c.truncate(a,b,e,k))}};b.EllipsisLegacy=function(){var a=this;this.observer=new ResizeObserver(function(b,d){b.forEach(function(b){var c=b.target.__nativendoContent__;a.truncate(b.target.__nativendoContainer__,c,c.__nativendoBreakWord__)})})};b.EllipsisLegacy.prototype=
{isTextOverflowing:function(a){var b={overflow:a.style.overflow,"overflow-y":a.style["overflow-y"],"max-height":a.style["max-height"],height:a.style.height};a.style.setProperty("overflow-y","visible","important");a.style.setProperty("max-height","none","important");a.style.setProperty("height","auto","important");var d=a.clientHeight;a.style.setProperty("overflow-y",b["overflow-y"]);a.style.setProperty("max-height",b["max-height"]);a.style.setProperty("height",b.height);a.style.setProperty("overflow",
"hidden","important");d=a.clientHeight<d;a.style.setProperty("overflow",b.overflow);return d},truncate:function(a,b,d){var c;if(a){b=b||a;b.__nativendoTruncateText__?b.innerText=b.__nativendoTruncateText__:b.__nativendoTruncateText__=b.innerText;var e=b.innerText.length;d=d||!1;if(this.isTextOverflowing(a)){for(c=0;this.isTextOverflowing(a)&&0<e&&1E3>c;)c++,e--,b.innerText=b.innerText.substring(0,e);a=b.innerText;if(d)a=a.substring(0,a.length-4);else{d=e;c=0;do{c++;var m=a.lastIndexOf(" ",e-1);-1<
m&&(a=a.substring(0,m),e=a.length)}while(-1<m&&m>d-4&&1E3>c)}0<a.length&&(a+=" ...");b.innerText=a}}},truncateOnLoad:function(a,b,d,e){var c=this;a&&(b=b||a,doc=a.ownerDocument,win=doc.defaultView||doc.parentWindow,b.__nativendoBreakWord__=e,b.__nativendoContainer__=a,b.__nativendoContent__=b,win.addEventListener("load",function(){c.truncate(a,b,e)}),win.addEventListener("resize",function(){c.truncate(a,b,e)}),d.forEach(function(d){d.addEventListener("load",function(){c.truncate(a,b,e)});d.__nativendoObserveResize__||
(d.__nativendoContainer__=a,d.__nativendoContent__=b,d.__nativendoObserveResize__=!0,c.observer.observe(d))}),b.__nativendoObserveResize__||(b.__nativendoObserveResize__=!0,c.observer.observe(b)),a.__nativendoObserveResize__||(a.__nativendoContainer__=a,a.__nativendoContent__=b,a.__nativendoObserveResize__=!0,c.observer.observe(a)),c.truncate(a,b,e))}};b.ellipsis=new b.Ellipsis;b.visibilityObserver=new b.VisibilityObserver({debug:e["nativendo_"+b.uniqueId+"_conf"]&&"dev"==e["nativendo_"+b.uniqueId+
"_conf"].env})}})(window,document,document.head||document.getElementsByTagName("head")[0],document.getElementsByTagName("body")[0]||document.body);
window.NativendoV2Loader=function(){function e(e){return function(m,r,w,q){r="undefined"==typeof r?!0:r;w="undefined"==typeof w?{}:w;q="undefined"===typeof q?document:q;return new Promise(function(b,a){setTimeout(function(){var c=q.createElement("pixel"==e?"img":e),d="body",f="src";c.onload=function(){b(m)};c.onerror=function(b){a(m+" / "+window.location.href)};c.onabort=function(b){a(m+" / "+window.location.href)};switch(e){case "script":c.async=r;preloadType="script";break;case "link":c.type="text/css";
c.rel="stylesheet";preloadType="style";f="href";d="head";break;case "pixel":c.style="position:absolute;visibility:hidden;width:1px;height:1px;",preloadType="image"}c[f]=m;if(!navigator.userAgent.match(/(edge\/|mobile\/|android\/)/i))try{var k=q.createElement("link");k.href=m;k.rel="preload";k.as=preloadType;q.head.appendChild(k)}catch(p){}try{Object.keys(w).forEach(function(a){c.setAttribute(a,w[a])})}catch(p){}try{q[d]||"body"!=d||(d="head"),q[d].appendChild(c)}catch(p){a(m+"/ "+p+" / "+window.location.href)}},
0)})}}return{css:e("link"),js:e("script"),img:e("img"),pixel:e("pixel"),request:function(){return function(e,u,r,w,q,b,a){b="undefined"==typeof b?2500:b;a="undefined"==typeof a?"":a;return new Promise(function(c,d){var f=new XMLHttpRequest;f.open(e,u,"undefined"==typeof q?!0:q);f.withCredentials=!0;f.timeout=b;a||"post"!=e.toLowerCase()||(a="application/x-www-form-urlencoded");a&&f.setRequestHeader("Content-type",a);f.onreadystatechange=function(){f.readyState==XMLHttpRequest.DONE&&("function"==typeof w&&
w(f.responseText,f.status),c(u))};r?f.send(r):f.send()})}}()}}();
(function(e,m){e.nativendo=e.nativendo||{};for(var u=m.querySelectorAll("script[data-nativendo-instance]"),r=u.length,w=0;r>w;w++)(function(q){if(q&&"undefined"==typeof e.nativendo[q]){var b=e["nativendo_"+q+"_conf"];e.nativendo[q]=new NativendoV2(b);e["nativendo_"+q]=nativendo[q];if(b.external)b.data&&(new e.nativendo[q].Observer).monitor(b.data);else{b.dmp.forEach(function(a){if("undefined"==typeof a.endpoint)"undefined"==typeof e[a.type+"_segments"]&&(e[a.type+"_segments"]="");else{var c=e[a.type+
"_segments"]="";a.callback&&(c="nativendo_dmp_"+a.type,e[c]=function(b){try{switch(a.type){case "theadex":if("string"==typeof b&&(b=JSON.parse(b),b.data&&b.data.attributes&&b.data.attributes.segments&&b.data.attributes.segments.length)){b=b.data.attributes.segments;break}case "nativendo":b=b["segment-ids"]&&b["segment-ids"].length?b["segment-ids"]:!1;break;default:b=!1}b&&(e[a.type+"_segments"]||(e[a.type+"_segments"]=[]),e[a.type+"_segments"]=e[a.type+"_segments"].concat(b))}catch(E){console.debug(E)}});
var d="",f="",g="";b.gdpr&&(d=e.nativendo[q].gdpr,f=e.nativendo[q].gdprPd,g=e.nativendo[q].gdprConsent);0<a.endpoint.indexOf("{CALLBACK}")?NativendoV2Loader.js(a.endpoint.replace("{CALLBACK}",c).replace("${GDPR}",d).replace("${GDPR_PD}",f).replace(/\$\{GDPR_CONSENT(_\d+)?\}/g,g)):NativendoV2Loader.request("GET",a.endpoint.replace("${GDPR}",d).replace("${GDPR_PD}",f).replace(/\$\{GDPR_CONSENT(_\d+)?\}/g,g),!1,e[c])}});var a=[NativendoV2Loader.css(b.endpoints.c+b.path.css+"nativendo.css"+b.cq,!0,{id:"nativendo-css-link"})],
c=[];if(e.top!==e)try{e.top.document;if(e.top.document.getElementById("nativendo-css-link"))throw"css already available in top";a.push(NativendoV2Loader.css(b.endpoints.c+b.path.css+"nativendo.css"+b.cq,!0,{id:"nativendo-css-link"},e.top.document))}catch(g){}m.evaluate||a.push(NativendoV2Loader.js(b.endpoints.c+b.path.js+"wgx.js"+b.cq));var d=e.location.hash.match(e.nativendo[q].hashRegex),f=e.location.hash.match(/\/([a-z0-9]+)\/aid\/(\d+)\/cid\/(\d+)\/?(preview|heatmap|clickmap)?/i),k="";f&&f[1]==
b.identifier&&(d=["",q,0==f[2]?0:parseInt(f[2]+""<<8,10).toString(36),parseInt(f[3]+""<<8,10).toString(36),"0",f[4]]);d&&(d[1]==q?(k=d.slice(2,5).join("/"),c.push("reco=1"),d[5]&&"lineup"==d[5]||a.push(NativendoV2Loader.css(b.endpoints.c+b.path.css+"content.css"+b.cq))):d=!1);"undefined"!=typeof b.p.path&&(k=b.p.path);a.push(new Promise(function(a,d){try{-1<b.abc&&(0<b.abc&&(c.push("ab=1"),c.push("ig[]=500")),a());var e=m.createElement("DIV");e.id="sponsorText";e.style.position="absolute";e.style.left=
"-999px";e.appendChild(m.createTextNode("&nbsp;"));var f=!1,g=0,h=setInterval(function(){if(!f){var b=m.getElementsByTagName("body")[0];if("undefined"==typeof b)return;b.appendChild(e);f=!0}++g;0==e.clientHeight&&(c.push("ab=1"),c.push("ig[]=500"));if(3<=g||0==e.clientHeight){clearInterval(h);try{m.getElementsByTagName("body")[0].removeChild(e)}catch(B){}a()}},16);setTimeout(function(){f||(c.push("ab=1"),c.push("ig[]=500"));h&&clearInterval(h);a()},1600)}catch(E){a()}}));var p=function(){var a=new e.nativendo[q].URL,
m=[];b.dmp.forEach(function(a){-1==m.indexOf(a.type)&&e[a.type+"_segments"]&&(m.push(a.type),c.push(a.type+"="+JSON.stringify(e[a.type+"_segments"])))});"undefined"!=typeof b.p&&"undefined"!=typeof b.p.url||c.push("url="+a.encode(e.nativendo[q].currentUrl));b.gdpr&&(c.push("gdpr="+e.nativendo[q].gdpr),c.push("gdpr_pd="+e.nativendo[q].gdprPd),c.push("gdpr_consent="+e.nativendo[q].gdprConsent));try{Object.keys(b.p).forEach(function(d){var e=b.p[d];e="object"===typeof e?JSON.stringify(e):a.encode(e);
c.push(d+"="+e)})}catch(t){}e!==e.parent&&c.push("if=1");"undefined"!==typeof e.context&&"AMP-AD"==e.context.tagName&&c.push("amp=1");var n;try{var p=e.top.document.querySelector('link[rel="canonical"]');p&&(n=p.getAttribute("href"))&&n!=e.nativendo[q].currentUrl&&c.push("canonical="+a.encode(n))}catch(t){}e["nativendo_"+q+"_conf"]&&e["nativendo_"+q+"_conf"].jobs&&e["nativendo_"+q+"_conf"].jobs.before_get&&e["nativendo_"+q+"_conf"].jobs.before_get.forEach(function(a,b){a()});Promise.all([NativendoV2Loader.request("POST",
b.endpoints.d+"/cds/delivery/get/"+k,c.join("&"),function(a,b){try{eval(a)}catch(E){}},!0,1E4)]).then(function(){try{NativendoNlpFeature&&b.endpoints.n&&e["nativendo_"+q+"_map"]&&e["nativendo_"+q+"_map"].w&&(new nativendo[q].NLP).categorize(b.endpoints.n,e["nativendo_"+q+"_map"].w,n&&n!=e.nativendo[q].currentUrl?n:e.nativendo[q].currentUrl);var c=d&&d[5]&&-1==["lineup"].indexOf(d[5])?d[5]:"normal",g=d&&d[5]&&"lineup"==d[5]?1:0,m=d&&d[2]&&"0"==d[2]||f?a.encode(e.nativendo[q].currentUrl):!1,p=c;c.match(/survey|story/)&&
(c="normal");nativendo[q].setTrackMode(c);if(d){nativendo[q].setHashParts(d);c=null;try{e["nativendo_"+q+"_map"].id&&(c=e["nativendo_"+q+"_map"].id)}catch(C){}NativendoV2Loader.js(b.endpoints.d+"/cds/delivery/content/"+k+"?tm="+p+(c?"&rid="+c:"")+(g?"&lu="+g:"")+(m?"&url="+m:"")+"&gdpr="+e.nativendo[q].gdpr+"&gdpr_pd="+e.nativendo[q].gdprPd+"&gdpr_consent="+e.nativendo[q].gdprConsent+"&m=0")}nativendo[q].findNodesAndRender()}catch(C){console.debug(C)}}).catch(function(a){})};Promise.all(a).then(function(){setTimeout(p,
0<b.dmp.length?150:0)}).catch(function(a){console.debug(a)})}}})(u[w].getAttribute("data-nativendo-instance"))})(window,document);
